### ISSUE TITLE
High data usage when using Dropbox

### ISSUE THREAD

**Issue by paranerd** [PhilippC/keepass2android#1012]
Hi all,

I recently set up Dropbox sync and have noticed very high data usage from keepass2android. Do you download the vault from Dropbox at each start to compare it with the cached copy? If so: is there a setting to disable this behavior?

Thanks for your amazing work!

**Comment by PhilippC** [comment]
I suggest you enable "Work or internal cache only" which means that the app never accesses the remote database unless you explicitly switch this off again. Does this solve the issue for you?

**Comment by usnbrendon** [comment]
Philipp, 
This suggestion rather confounds me, kind sir.  Might I inquire as to why / how this is a suitable solution?  

I ask with the general premise in mind that an individual (such as myself) has the unique & unequivocal requirement of maintaining KP2A to KP2 (x86) sync utilizing cloud storage (specifically Dropbox) between and/or installed upon my many devices to:
1) keep my kbdx readily available 24/7/365,

2) keep kbdx always up to date with latest change(s) / password additions regardless of what device(s) I am actively utilizing, and 

3) assuring that I always have a current uncorrupted kbdx file accessible from the www provided that my local cached copy fails decryption or otherwise becomes damaged and in need of replacement.

As a sidenote, I noticed what I thought was an unusually long delay between auto updating/saving kbdx prior to being able to use it for autofill etc., in real time daily activities.  Thus I did some research and attempted utilizing other FREE cloud storage options such as pCloud that either do not have UPLOAD speed limitations or that have much higher throughput on cloud servers.    The hope being (with any luck) that's I'd notice a marked decrease in the amount of time stuck WAITING for KP2A to complete a new key addition/change to my database resulting in the app doing autosync / compare / verify operations--which as you are well aware steals app focus & disallows other operations within the application including AUTOFILL of the newly added or modified passkey--resulting in a frustrating (sometimes upwards of 90-120 seconds) long down time that significantly impacts workflow & sadly, in several cases over the past 2 years I get stuck having to ask someone on the phone CSR our tech support to wait for what seems like forever until I can provide the data they requested from my keyfile or I hold up the line in a store or elsewhere just staring at my phone & apologizing to everyone behind me until KP2A finishes up its background work & gives me back control and access to my keyfile.    

Sadly, though pCloud did not impose the UPSTREAM bandwidth speed limitation unlike Dropbox, it became apparent that any time saved was insignificant in practical terms.....largely because it seems the sheer size of my kbdx file has grown so much over the past 7 years that KP2A simply cannot work any faster while performing the encryption using the recommended default algorithm and number of derivations / rounds during sync to cloud.  It wasn't noticeably faster when only working on LOCAL CACHED file, even on Galaxy S10!   Leaving me wondering what the best + most effective way is to reduce kbdx file size is while retaining convenience & access to all my needed data.   

Any help in this regard is highly appreciated.  And, with regard to the original comment thread, I too wish to understand / comprehend WHY there would be excessively high transmission of data between cloud storage and that which is required to perform the same functions locally.   I haven't noticed this specifically--but the original comment seems entirely valid, whereas the solution you proposed does not appear to address the problem at hand....unless I'm misunderstanding the nature of the original comment & what it was attempting to convey
Thanks

**Comment by PhilippC** [comment]
@usnbrendon the OP asked whether KP2A downloads the file from remote storage at each startup - the answer is yes and turning this off reduces high data usage. This comes at the cost that you need to trigger sync manually, but it is totally possible to work with this.

I don't think KP2A has "excessively high transmission of data" for reasonably small databases. Please use Keepass2 on PC to view the size of each entry, remove attachments (including history) or export to XML to see the size even better. If loading speed concerns you, you might also want to try to change the key transformation settings.

**Comment by paranerd** [comment]
I actually tried setting it to use the internal cache only, but checking the checkbox on the "login" screen causes the app to crash when opening the database :-/

**Comment by Karreg** [comment]
Also it looks like to me that the issue may be the encryption configuration.

I suggest you switch to Argon2, because KP2A performances on Argon2 are now similar to those of KeePass2. I was able to use the parameters given by KeePass2 without having to tweak them for opening in KP2A.
However, if you want to stick to AES-KDF, you should remove one digit from the number given by KeePass2 with the `1 seconde delay` button, to have a opening/saving delay humanly acceptable in KP2A. The value will still be far more better than default value...

**Comment by paranerd** [comment]
Converted my Database to using argon2 with the 1 Second Delay as suggested. Nothing changed.

Steps to reproduce:
(1) Upload database to Dropbox
(2) Connect KP2A to Dropbox
(3) Load database for the first time
(4) From the dropdown menu select "Use internal cache only"
(5) Lock database
(6) With "Internal cache only" checked try to load database
... crash.

**Comment by Karreg** [comment]
Sorry for the misunderstanding but I was answering to @usnbrendon... :)

**Comment by usnbrendon** [comment]
> Also it looks like to me that the issue may be the encryption configuration.
> 
> I suggest you switch to Argon2, because KP2A performances on Argon2 are now similar to those of KeePass2. I was able to use the parameters given by KeePass2 without having to tweak them for opening in KP2A.
> However, if you want to stick to AES-KDF, you should remove one digit from the number given by KeePass2 with the `1 seconde delay` button, to have a opening/saving delay humanly acceptable in KP2A. The value will still be far more better than default value...



> Sorry for the misunderstanding but I was answering to @usnbrendon... :)

Grėgory,

Thank you, very much for taking the time to read my post (which I now realize ended up not being related to OP's original post & for that I apologize to all within the thread).  Further, I greatly appreciate that you apparently recognized the likely source of my unacceptably lengthy sync/save times when using KP2A.   I believe I understand your suggestion & the instructions you provided in your recommendation; however, I am less certain of the reasoning behind your suggested change to the encryption method / derivation.   This I believe is due to my lack of deep understanding of some of the more granular and perhaps what ultimately are some fairly important user-definable parameters, which can result in perhaps significant improvement / enhancement of KP2A performance.   Clearly, I'd do well to find the pertinent documentation and/or forum threads that address the encryption derivation settings and how + why various tweaks to these parameters result in both desirable & potentially quite undesirable behaviors in KP2A specifically.

I am grateful for any suggested resources you might point me towards as a solid primer to get me up to speed; otherwise any generalized personal 'wisdom' you don't mind sharing with me will be thoroughly devoured as I dig into this further!

Philipp, thanks to you as well for your time and consideration.  My gratitude for all that you do is profound indeed, sir! 

Cheers
