### ISSUE TITLE
Support large files on OneDrive

### ISSUE THREAD

**Issue by PhilippC** [PhilippC/keepass2android#1036]
According to https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0, files > 10MB must be uploaded with an upload session. KP2A currently fails to upload large files.

**Comment by lostgit** [comment]
I'm voting for this as this is a biggie for us OneDrive user. 

For documentation, pls see my comment from #1158 https://github.com/PhilippC/keepass2android/issues/1158#issuecomment-591230654

The limit seems to be 4 MB instead of the documented 10 MB. My file was 6.5 MB and it kept failing with K2A 1.07 & 1.08 until I experimented and truncated entries to reduce it to under 4 MB. It was fine with the previous API before K2A switched to MS Graph API. For now, am going to revert to older version. 

Thanks as always - I'll continue to donate now and then as I appreciate your efforts.

**Comment by lostgit** [comment]
Reverted to KeePass2Android 1.07R1 and large files work with OneDrive

APK here: https://www.apkmirror.com/apk/philipp-crocoll-croco-apps/keepass2android-password-safe/keepass2android-password-safe-1-07-r1-release/

**Comment by wwillm** [comment]
With 1.08b-pre2 we get the same error when updating a 6.3 MB password file

**Comment by Mellelmejor** [comment]
Hello @PhilippC 
Are there any plans to solve this issue? I am unable to sync my databases now because of size limitation. I will try the older versions as suggested, but that again would be an issue as the older versions do not support Brave browser Autofill.

Are there any other alternatives to solve this problem?

**Comment by lostgit** [comment]
@Mellelmejor, icymi: "PhilippC added this to the 1.09 milestone on Nov 12, 2019" - that's his plan.

**Comment by lostgit** [comment]
I'd throw this in here: 

[Upload large files using the Microsoft Graph SDKs May 2021](https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=csharp)

**Comment by lostgit** [comment]
1.09a fixed this issue.
