### ISSUE TITLE
Argon2 key derivation function really slow

### ISSUE THREAD

**Issue by Daniel9132** [PhilippC/keepass2android#106]
Hello,
recently i wanted to improve the security of my database by using the Argon2 key derivation function instead of the standard AES-KDF but somehow Argon2 is really slow on my smartphone.
I did some testing (keepass2android 1.02):
I tried both AES-KDF and Argon2 and set them up on my Desktop PC to have a 1,5sec delay.
On my Smartphone (Samsung S7 Exynos version) that resulted in a 7 sec Delay with AES-KDF and 32 sec with Argon2.
I wanted to suggest to improve the Argon2 performance, if possible. It provides improved security but the long delay makes it not useable so i had to switch back to AES-KDF.

**Comment by YellowOnion** [comment]
I know this is not a fix, but as a work around set your parallelism to the amount of CPUs you have on your phone (8 or 4) and keep the memory usage under the Size of the L2 cache of the phone.

For example with 800 rounds, 1MB, and parallelism 8 works on my phone (Krait 400) is 13s, and 0.5s on my desktop (i5 3570)

I've been curious about the performance issue on phones as well, It's probably related to slow mono performance on arm, and/or 32bit application since Argon2 is built off of BLAKE which was designed for 64bit systems.

**Comment by Daniel9132** [comment]
Sacrificing security for convenience is not really my intention since there is something clearly wrong with argon2 on keepass2android.
My phone is completely 64bit from hardware to software, and since argon2 is a memory-hard function it should perform better with faster memory right?
My Desktop PC has DDR3-1333 RAM and my phone has LPDDR4 with more than 2000, so it should perform better on my phone but it is clearly not.
I just wanted to suggest to have a look on that because GPU/ASIC attacks keep getting more common and argon2 was implemented for exactly that reason so i want to use it on all my platforms but right now the drawbacks are too big on android.

**Comment by YellowOnion** [comment]
@Daniel9132 ARM64 is backward compatible with 32bit apps, it's quite possible that KP2A is using the 32 bit mono runtime.

How much memory are you using? the default is 1MB, and that fits into L3 cache on modern desktops & cellphones, it's not hitting your memory.

Put parallelism up to 4, and then crank up the memory usage to 128MB, and use about 20 rounds, if you're worried about GPU / ASICs being used to crack your database, the best way to waste silicone is exhausting memory as quickly as possible.
