### ISSUE TITLE
Syncing (back) to google drive does not work anymore

### ISSUE THREAD

**Issue by arduinoProjz** [PhilippC/keepass2android#108]
Hey, 

i have same issus as reported here: https://keepass2android.codeplex.com/workitem/757

My keepass2android pws app does not sync items back to google drive.. I using this app long time ago, i just got wonder why do i do not see new entries (creatde on my android phone) on my PC.  App says db is sync, but it is not. Timestamp of the file is Sep 17, 2017, but I created couple of entries later on my phone. 

Normally I edit/add entries only on my android phone, and use them on my PC maschine. 
I have exported db file from my mobile phone to drive and saved it under new name. When I open this file thhrough KeePass on my PC i see the new entries. So somehow the syncing from keepass2android back to drive went wrong. It does work only locally. I habe tried to switch to "work offline" and than baxk "work online" but it does not work.

Any ideas?

I think/hope when I reinstall the app on my phone it will work... I will try it now.

**Comment by arduinoProjz** [comment]
I have clear the cache on app and reinstalled it on my mobile phone. Now it is working again.  Changes get propagated from k2a app to google drive and vice versa.

Strange...I dont know what was the reason for that, and it does not make my happy. Is is possible that that db file got corrupted on google drive? or is the app buggy and says that sync is ok also in case there is some error in this process. could someone check it, please?

thank you in advance

Pavol

**Comment by PhilippC** [comment]
can you double check your Google drive if there might be a second file with the same name or so (this still might be an app bug then but might help to track it down)?

**Comment by arduinoProjz** [comment]
Hey Philipp,

it is strange, My DB-name is pavol.kdbx. I have been using this file for couple of years...

I have found one entry with name "pavol.kdbx"  in trash of my google drive. It was created back in 2014 and moved to trash on July 25th and the history says , that this file was modified after move to trash. WTF?

My actual pavol.kdbx file was uploaded to drive on July 25th. It does not make sense. So something happend in July?! Somehow keepass2android has used db file from trash....and not the actual file...

In July I bought my Samsung S7 mobile phone and i move all my apps and data from Nexus 5X to Samsung S7. (backup/restore) . The July 25th could be a date when I port my data....

Facts::
My actual db file "pavol.kdbx"
- was uploaded(not created!) to google drive on July 25th (It does not make sense, because I have using this file for couple of years)

Entry "pavol.kdbx" in trash
- was created in 2014 (it makes sense!)
-was moved to trash on July 25th (it does not make sense, but could be date on which i made restore on my new android device)
-history shows that this file was modified afterwards (in august and september, it looks like keepass2android somehow used the entry from trash, which answers the question why the file was in "sync" but i havent seen the changes neither in google drive nor on my PC)

So Philipp, you are right, there are 2 files in google drive (one actual and one in trash), but something is buggy... Google drive should not allow to modify file in trash and somehow keepass2android made it possible to create 2nd instance of this file....

sincerely yours,
Pavol

**Comment by PhilippC** [comment]
Google Drive is not a drive which is based on folders and files with filenames, even though this seems to be the case. In fact, you can have two files with the same name in the same folder. They have a unique id and this ID is what KP2A gets/needs to access the file. I cannot use the file name because (as said) this is not unique. Moving to trash simply means moving to another folder, and as KP2A still has the "handle" (ID) of the old file, that's the way it works in GDrive. I can recommend moving to Dropbox which has an API which makes things work better.

**Comment by kribjo** [comment]
I also stumbled into this problem. I think it should be in some FAQ/troubleshooting/good-to-know documentation since it is very devious in behavior and difficult to figure out for the user.

**Comment by SilverKnightVGM** [comment]
Also just encountered this problem for the first time. Found the modified file in trash, while the unmodified one was still in its folder; just moved it over and deleted the extra one and it worked just fine without uninstalling the app.

**Comment by kidpixo** [comment]
I had this problem as many others, I can summarise as:

- open a DB from GDrive from a Location (not Trash)
- make some changes
- save
- open from other device and find no update
- find the DB in Gdrive Trash
- restore it
- [repeat it on every change with keepass2android]

As @PhilippC  comment above, it is a normal behaviour for GDrive.
I found this issue "[Shared files are moved to trash when changed locally · Issue #122 · astrada/google-drive-ocamlfuse](https://github.com/astrada/google-drive-ocamlfuse/issues/122)"
 that could solve the issue, simply set `Use file transactions for writing databases` to no.

I have no idea it this could potentially be dangerous, I don't know what happens if you write a corrupted DB without a temporary file.
