### ISSUE TITLE
Can't open a database synchronized via FTP

### ISSUE THREAD

**Issue by kromkrom** [PhilippC/keepass2android#1094]
Version is 1.08-pre3 which I installed to test out https://github.com/PhilippC/keepass2android/issues/1040

1. Source and cache files are successfully synchronized via FTP
2. When trying to unlock a database (which I was able to unlock without any problems before update and hadn't had any editing in it), a message "An error occured: Root element is missing".
3. Desktop KeePass is able to open the database. Resaving and resynching doesn't help. Local backup can be opened too.

**Comment by krethjr** [comment]
Auto updated to KeyPass2Android version 1.08-r1 this morning Feb 19, 2020 is causing this same issue on my Pixel v1 with Android 10 Build# QP1A.191005.007.A3

I reinstalled from scratch.  Was able to reach my ftp server for my keystore OK.  I attempt to unlock with my password and get popup error "An error occured: root element is missing"

**Comment by PhilippC** [comment]
is this a publicly reachable FTP server. Is it possible to get a test account on it?

**Comment by krethjr** [comment]
Philipp,

Yes, here is a temporary login to my ftp server:

Server:  ftp.krethweb.org  - default port

login: philippc@krethweb.org

Password: 5=P9AaUA4F

This account is limited in file size and will be shut down in 7 days 
(2/26/20)

Jim Kreth
jim@krethweb.org

**Comment by PhilippC** [comment]
not sure if you are aware that this was posted publicly on Github? You can also send credentials to crocoapps@gmail.com. Unfortunately I am currently struggling to build the app (after updating some tools) so I didn't have the chance to look at it yet.

**Comment by PhilippC** [comment]
Hi @krethjr, I finally fixed my build issues and now am able to test again. I tried to connect but in addition to a certificate warning (hostname not matching) I got login failed - probably because the credentials are no longer valid. 
Could you send me new credentials by email, maybe? Can you also try to see if you can fix the certificate issue - maybe that's causing the problem which you have?

**Comment by StefanPp** [comment]
Same problem on my Nokia with Android 10
00WW_4_088_SP03
The kdbx is on ftp Server port 21. Same file on local storage: no problem. Only via FTP causes the "An error occured: Root element is missing".
Do you need access to FTP directory? Its my server, I can provide you with creds.

**Comment by PhilippC** [comment]
@StefanPp Yes, I'd like to take a look. Can you send the credentials to crocoapps@gmail.com?

**Comment by doubleamp** [comment]
I have this same problem since some days ago. Trying to open a database in a FTP server, correctly receiving updates from desktop Keepass, yields a 'Root element is missing' error in keepass2android.

**Comment by PhilippC** [comment]
please switch to 1.08b-pre2: https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by doubleamp** [comment]
Yup, thank you, now it is working again!

**Comment by Vexarmor** [comment]
Hi Philipp,
No problem with Xiaomi Redmi Note 7 and others Phone
Same problem whith Xiaomi Redmi Note 8 pro (for 2, 3 or more weeks)

Problem resolved whith Xiaomi Redmi Note 8 pro whith1.08b-pre2

Thanks a lot, it deserves a great cold beer, it is done

**Comment by proudiere** [comment]
Hello, 
I had exactly and suddenly same issue on my Mi2 lite then on my tablet Huawei T5 .
Both solved with 1.08b-pre2 :-)

Something puzzles me  (probably because  I'm computer engineer and work sometimes on software incident ! )  : As I didn't change anything on my devices (no update of application) and as I didn't change anything on my database ... what is the cause of the issue ? A change in FTP configuration on my provider (OVH) ?

Philippe

**Comment by zepingouin** [comment]
Hello,

Solved with the beta release 1.08b-pre2 on my provider FREE.
Hot weather is coming, you deserve a fresh beer !

Gérard
