### ISSUE TITLE
Where is my Keepass database synced to??

### ISSUE THREAD

**Issue by TheKirkwoods** [PhilippC/keepass2android#127]
I am in a position where I would like to store my Keepass database on Google Drive.  This way, I can sync the database between all of my devices, and my wife's devices as well.

First things first...where IS my database right now?  How do I locate it?  Next, how do I get it to the Google Drive correctly?  Do I just move the file?  I use Keepass2Android on my phone.  I can't figure out for the life of me how I determine the correct database location, or better yet, how to point the application with a different location, such as pointing it toward a location of the Google Drive.  At this moment, when I hit "Synchronize Database", I have no idea 'where' it actually syncs up from.  Hopefully not from Russia.  LOL

Thanks!

**Comment by Wuestengecko** [comment]
You should be able to see the database path in the "Unlock Database" dialog (not QuickUnlock). You might have to pull that window down in order to see the path. You should also see it in the recent databases list if you select "Change database" from the menu.

For switching to Google Drive, see [the page about Dropbox synchronization](https://keepass.info/help/kb/trigger_examples.html#dbsync) on the official Keepass website - it really applies to any cloud storage service you might want. In KP2A you don't have to set up any triggers yourself, it should behave like that automatically if you just open the file via KP2A's Drive interface.

**Comment by PhilippC** [comment]
you can create a copy of the file on GDrive if you go to Database settings -> Export -> Google Drive. After that, lock & close the database, then tap "Change database" -> "Open database" -> Google Drive and open the file from there again.
