### ISSUE TITLE
Database doesn't synchronize automatically

### ISSUE THREAD

**Issue by anishmittal2020** [PhilippC/keepass2android#1298]
I use the offline version of the Android app on Android 10.  I use another app (Syncthing) to synchronize the database from my Laptop to my phone, which happens periodically every hour. But the changes made, doesn't get syncronized automatically (even after we have closed all apps and I restart the Android app), we have to manually press "Syncronize database".

## Expected Behavior

Atleast when the app is closed and reopened, then it should syncronize.

**Comment by PhilippC** [comment]
how exactly did you open the file in the app?

**Comment by anishmittal2020** [comment]
I click the button *Open File...* Which is located above *Cream ta te new database...* In the offline app.

**Comment by PhilippC** [comment]
and what exactly do you do then? Use a third party app or the Android file picker? Please try both approaches and see what works better for you.

**Comment by anishmittal2020** [comment]
Ok. I will do that the next  time and let you what happens. Many thanks for the app.

**Comment by anishmittal2020** [comment]
I used third party app approach as you said. I think this is working better. I would update you if changes get synchronised or not.

**Comment by ChrisJan00** [comment]
+1 I have the same problem.  When I open the app, there is a context menu with an option "Synchronize database...".  If I click on it, there's a nag pop-up like "do you really want to?", and then it synchronizes the database and all is good.  The problem is that I have to remember to manually go through all these steps every time I change something.

The solution would be that this option is run automatically when I open the app, instead of requiring a manual action each time. 

I tried enabling and disabling the following:
Settings > App > File handling >  Database caching
Settings > App > File handling >  Local backups

But none of those options seem to make a difference.  The local copy is never synchronized. I have to do it manually. I have already run into merge conflicts between the local database and the remote one a couple of times because of this.

Importing: The database is a keepass2 file coming from another device (my laptop), which is synchronized into the file system with a 3rd party app. I imported it here through the standard Android file picker.  If I click on "Open another database"  this one shows in the app's list of recent databases as "content://mypwdb.kdbx".  I don't know if this info helps.

**Comment by PhilippC** [comment]
it seems to me like this is more a problem of how syncthing syncs/provides the file. If the content:// URL is used later but doesn't get fresh data, the app cannot solve this.

**Comment by 1aladdin1** [comment]
I have the same issue as @ChrisJan00 

I'm using Syncthing for Peer2Peer synchronisation of my kdbx-database between desktop (running Ubuntu) and smartphone (running Android 11). After changing kdbx-content at desktop, syncthing works as expected and syncs this kdbx-file to my smartphone.

Keepass2Android is configured to NOT use caching or local backup.
When I now try to read the previosly changed kdbx-content on my smartphone, Keepass2Android still uses some sort of cache and seems not to know anything about the previosly changed kdbx-content. I have to manually command Keepass2Android to sync its database - then the previosly changed kdbx-content is shown as expected.

**Comment by hackel** [comment]
I'm also experiencing this issue accessing a database on Google Drive via the SAF.

Ideally, I would like an option for keepass2android to always attempt to sync on every startup/quick unlock, and only if unable to do so, use the cached database.  In this case, it should show a warning so that I know not to change anything until connectivity is restored.  It's not clear to me if a sync is performed prior to writing in order to detect/merge incoming changes in this situation.

**Comment by Kenneth-C-W** [comment]
PhilippC - Thank you for your efforts in developing and maintaining this app. It is very much appreciated. 

I agree with several of these other users and would welcome an enhancement to be able to auto syncronize from the master database file on open or successful login. 

Plan A: My wife and I attempted to share the database file from my Google Drive acct but found that does not seem to keep the files in sync due to what appears to be a limitation of Google Drive. 

Plan B: We are now using the WebDav internet url to the master database file on our Synology NAS to access the database file remotely (from phones and pcs) and keep them synced between us. This works well but requires us to manually select the syncronize database option to ensure we have the latest version.

Hoping an new user preference option could be enabled / disabled to allow this function as a future enhancement / feature request .

Thanks again
Kenneth
Omaha, NE, USA

**Comment by PhilippC** [comment]
BTW there is the menu option to sync always after QuickUnlock. Does this solve this issue?

**Comment by ChrisJan00** [comment]
> BTW there is the menu option to sync always after QuickUnlock. Does this solve this issue?

In the last update, I am happy to see that this new option is mentioned in the "what's new" pop-up.
I tested it briefly this morning, and it seems to do the job. Awesome!
Thanks a lot for the good work :)
