### ISSUE TITLE
Ability to load the keepass file via webdav, with own certificate.

### ISSUE THREAD

**Issue by dseegers** [PhilippC/keepass2android#1305]
I have used the webdav function within Keepass2Android for a long time. Which of course works very well. Now I want to host the keepass file on my synology (nas). Now I can get the file via webdav, only this goes through a different port, so I can only offer it with a self-signed certificate.

Is it possible to ignore the check on this certificate (see if it is signed or not).
![Screenshot_20200701_121537_keepass2android keepass2android](https://user-images.githubusercontent.com/6848396/86233576-e71a4080-bb95-11ea-8210-75142fcc8027.jpg)

**Comment by mpas97** [comment]
Have you already tried to go into the settings (app settings->file handling->SSL certificates) and deactive the certificate check?
<img src="https://user-images.githubusercontent.com/9994218/86396944-2e422780-bca3-11ea-9675-db55ceab8da9.jpg" width="200">
<img src="https://user-images.githubusercontent.com/9994218/86396947-2f735480-bca3-11ea-8a04-d1ed2938cebc.jpg" width="200">

But as the hint says too, you probably rather should add the self-signed certificate to your phone, so it will be trusted.

Or why don't you just get a signed one? I use WebDav on my Synology NAS too, works perfectly fine :) Let's Encrypt is already integrated, so that should be straight forward.
<img width="400" alt="grafik" src="https://user-images.githubusercontent.com/9994218/86397634-7ca3f600-bca4-11ea-8052-377a1968a450.png">

**Comment by ViRb3** [comment]
Do __NOT__ ignore certificate validation, this is a huge security risk. Add your self-signed certificate to your Android phone's certificate store instead.

**Comment by dseegers** [comment]
I have added the certificate to my phone, and it is connecting using sftp

**Comment by iamdman** [comment]
> I have added the certificate to my phone, and it is connecting using sftp

Sorry to bring this back up I am in the same boat as you.  I put the cert from my NAS on my android but still no luck with WebDAV HTTPS.  In your post you said you were using WebDAV but then in your last comment you said you connected via sFTP, did you change your protocol to make this work?

**Comment by dseegers** [comment]
Well SFTP is still just ssh right 🍸, you can enable it on your nas / linux machine

**Comment by dseegers** [comment]
You could use a xxx.synology.me domain and add a certificate as well. Maybe that will work
