### ISSUE TITLE
Document access revoked exception

### ISSUE THREAD

**Issue by johnfoxii** [PhilippC/keepass2android#1382]
Hey Philipp,
Suddenly this morning I started seeing a popup message and app seemed to be using a cached version. I tried to update the local copy of the database and saw an access revoked message. 
To fix this I just went and reopened the database and it works fine now.

**Comment by PhilippC** [comment]
I think this requires no further action.

**Comment by JustMe567** [comment]
Hey Philipp,
I always get the keepass2android.Io.DocumentRevocedAccessException when I start the app. In the app settings I have deactivated local database cache and activated local database backup. Steps to reproduce the exception:
1. I use FreeFileSync to copy the latest database file of my notebook to my android device. The android device acts as an ftp server (run by the app Wifi FTP Server) and FreeFileSync copies the keepass database file via ftp to the android device (overwrites the old database file with the new on; same filename). 
2. I open keepass2android and enter my unlocking password --> the exception is thrown

Workaround: instead of step 2 choosing "change database" and manually select the same database file --> then opening this database works without exception. (until the database file is overwritten by a new version through ftp file transfer)

Although there is a manual workaround, it would be great if this topic were solved.

**Comment by PhilippC** [comment]
@JustMe567 If you have an FTP server (even on the Android) I suggest you go through FTP for accessing the file from KP2A also. Sharing files between apps is getting increasingly difficult on Android (due to security policy changes in the OS).

**Comment by JustMe567** [comment]
Hey Philipp,
thank you for your tip! But I find it a little cumbersome to go through an ftp server in order to acces a keepass database file which is stored locally on the same android device. Futrhermore I run the ftp server only during synchronisation with my windows pc. I don´t like being forced to have it running all the time (battery consumption and security aspects when connected to unsecure networks). 
Honestly I do not know anything about android file security policies, but if KP2A can access the database file after re-selecting it manually, why can´t the app access the file without re-selecting it? (or: wouldn´t it be possible for KP2A to "re-select" the file in the background/on app restart without requiring the user to navigate through the folder structure and clicking on the same file again?)

**Comment by PhilippC** [comment]
if you overwrite a file on Android, Android may revoke the permission to it and KP2A has no way to re-gain access to it without user interaction. I don't think this is a good setup for working with a file on two devices.

**Comment by markdmac** [comment]
I am having this issue.  I store my Keepass in my Google Drive so I can access the file from both my PC and from my phone.  Is there any workaround to this? I don't want my files getting out of sync.

**Comment by abatie** [comment]
I've also been using google drive as a backup; manually exporting works, but it's a royal pain and not as reliable as having it automatically sync like it used to
