### ISSUE TITLE
Full Biometric unlock tries to unlock with face unlock but doesn't work

### ISSUE THREAD

**Issue by KlaverBoer** [PhilippC/keepass2android#1392]
Since the last update 1.08b-r1 biometric unlock pops up my selfie camera (Xiaomi Mi 9T Pro) and tries to unlock using face unlock. But that doesn't work. 

When i'm opening the Keepass2android app i have to look away from the screen and unlock the database using my fingerprint. I do not want to use the selfiecam. Is it possible in a future release that i can choose which biometric unlock option i want to use? I only want to use the fingerprint option so that my selfie camera doesn't pop up. Versions prior than 1.08b-r1 didn't use the camera.

I'm using the app on a Xiaomi Mi 9T Pro running the Evolution-X rom.

**Comment by sambul13** [comment]
I'm using the same beta release with [Havoc 3.8](https://sourceforge.net/projects/havoc-os/files/kenzo/) (Android 10 AOSP based) on a Xiaomi phone, and don't see any option for Face Unlock, despite it works when unlocking the phone. Also, Fingerprint Unlock doesn't work throwing error "Failed to encrypt data" at attempt to  set it up.

I also think, Biometric Unlock should be offered in App Settings rather than DB Settings.

**Comment by PhilippC** [comment]
the current version is using Google's new authentication dialog which is the preferred way for these things. Biometric Unlock is a DB option because it needs to store the DB master password in secure storage. I would consider this a bug in the ROM, not the app.
