### ISSUE TITLE
 KeePassOTP Format integration

### ISSUE THREAD

**Issue by UsefulVid** [PhilippC/keepass2android#1401]
The old KeeOTP and TrayOTP Plugins for keepass are not actively developed.
There is a new Project:
https://github.com/Rookiestyle/KeePassOTP

KeePassOTP
Its support the migration from the old plugins but no Mobile App is compatible with its new OTP string.

`otpauth://totp?secret=xxxxxxxxxxxxxx&issuer=KeePassOTP`

Would be great to see keepass2android generating TOTP codes from the new format

**Comment by Rookiestyle** [comment]
KeePassOTP supports two different approaches for the otp-secret: [Details](https://github.com/Rookiestyle/KeePassOTP/wiki/KeePassOTP-storage-approaches)

For one of my databases where I store the secret in the format mentioned above, I don't experience this issue.
Only difference: I'm using `otpauth://totp/<label>?secret=xxxxxxxxxxxxxx&issuer=KeePassOTP`instead of `otpauth://totp?secret=xxxxxxxxxxxxxx&issuer=KeePassOTP`

According to https://github.com/google/google-authenticator/wiki/Key-Uri-Format#label the label is optional and may consists of either account name or issuer & account name

**Comment by UsefulVid** [comment]
> Can you try with adding a slash between totp and ?

This worked 👍
