### ISSUE TITLE
Use Sync.com to synchronize across devices?

### ISSUE THREAD

**Issue by BayBuoy** [PhilippC/keepass2android#1434]
Your main page says "The password database file can be synchronized across different devices. This works best using one of the built-in cloud storage options, but can also be performed with third-party apps."

I would like to use Sync.com to store my password database and synchronize across a PC, an Android phone and an Android tablet.

Sync.com is not one of the "built-in cloud storage options" but when opening a new database in keepass2android I seem to be able to access files stored in my Sync.com account through the Sync.com app on my Android device by selecting the "third party" option in keepass2android.

However, since you have said that keepass2android "works BEST using one of the built-in cloud storage options" I am wondering if using Sync.com will provide an inferior experience.

**Comment by PhilippC** [comment]
there is a request for this since very long (but with very little attention): https://github.com/PhilippC/keepass2android/issues/39

I haven't tested the sync.com app. The question is how it behaves 
* when the app changes the database file: will it detect this change and upload the changes? Some apps do this, some don't.
* when the app changes the database file, but at the same time (or while the phone was offline) another user/device also changed the database file - this means there is a conflict which cannot be solved by the Sync.com app because it cannot "look into" the database (it's protected - by design).

For the built-in cloud storage options, both questions can be answered: changes are uploaded when internet connection is available (if not, they are cached locally). When a change of the remote file is detected, the user is prompted to merge the changes (or take only one file if requested).
