### ISSUE TITLE
Can't change password, password corruption

### ISSUE THREAD

**Issue by GlassBeaver** [PhilippC/keepass2android#1436]
Once I change my password in keepass2android and close the database I can't unlock it again.
Using "Password + Challenge-Response for KeepassXC" with a Yubikey NEO.
The database is imported from my PC and I have no problem using it on Android if I don't change the password on Android.
I can change the password on the PC no problem.

Steps to reproduce:
1. Set a password and use Yubikey challenge-response on Windows PC
2. Copy KDBX database from Windows PC to Android
3. Open database on Android: type the password and use the Yubikey: this will work.
4. Change the master password on Android: Settings -> Database -> Change Master key
5. Lock & close the database and close the app
6. Try and login with the new password + Yubikey

**Comment by hertell** [comment]
The same goes if i try to open the passwordfile in a mac with MacPass.

The problem seems to be with non-numeric characters. I tested with a blank database, and set the password as 123. This i could open in MacPass, but as soon as there are characters involved, the file can't be opened in MacPass.

I wonder if it could have to do with encoding?
