### ISSUE TITLE
Keepass2Android nonet version synchronization problem

### ISSUE THREAD

**Issue by hjianhao** [PhilippC/keepass2android#1499]
On my PC, I use two files, one file for the local database, the other is for WebDav synchronization.  I use a trigger to synchronize the local database to the WebDAV database when "save" the local database. That works fine. When the database on WebDav changed, I can merge the local database and the WebDAV database by synchronization.

On an Android device, I use the "Folder Sync" APP to Synchronize the WebDAV database to local storage. Then I use Keepass2Android to open the local database.  But if I add an entry "A" on my PC, then Synchronized to WebDAV, and I add an entry "B" on my Android device. 

The "Folder Sync" APP pull the new database contains entry "A" to local storage, then I choose "Synchronize database" in Keepass2Android, then popup a dialog says that "source file changed, need to reload" when I press confirm button, then reload database then contains entry "A", but lose the entry "B".

So is there a method to merge the Keepass2Android changes to the database synchronized from WebDAV? not use overwrite Keepass2Android data by new pulled database?

**Comment by PhilippC** [comment]
KP2A shows this message it seems like it has already saved entry B, but then FolderSync overwrote the file with only change A in it. Maybe you can configure FolderSync to not overwrite the file. 
But the preferred solution is certainly to use the regular version instead of nonet and use the built-in WebDav support.
