### ISSUE TITLE
Invalid Composite Key (use Keyfile2.0)

### ISSUE THREAD

**Issue by BopSun** [PhilippC/keepass2android#1560]
Keepass2Android can't recognize the 2.0 keyfile I created, but version 1.0 can recognize it normally.

**Comment by Jabb0** [comment]
+1
I had the same issue with KeepassXC. Likely has something to do with Keepass now using XML keyfiles by default.
https://keepass.info/help/base/keys.html
https://github.com/keepassxreboot/keepassxc/pull/5798

KeepassXC still defaults to hashed binary keys unless you save the file as .keyx

**Comment by ulfkosack** [comment]
+1
I had to update two keyfiles to new hashed xml syntax since Keepass 2.47. I can't open these databases anymore. 

The xml syntax is correct (testet with Notepad++ XML Check), but differs a little bit

Old masterkey version 1.00
`<?xml version="1.0" encoding="utf-8"?>
<KeyFile>
	<Meta>
		<Version>1.00</Version>
	</Meta>
	<Key>
		<Data>Lt6foDBjrMaq5Qap20kvU8TO9++N9CXIs1MTMT7qmFc=</Data>
	</Key>
</KeyFile>`

New masterkey version is 2.00
`<?xml version="1.0" encoding="utf-8"?>
<KeyFile>
	<Meta>
		<Version>2.0</Version>
	</Meta>
	<Key>
		<Data Hash="D8685152">
			0C4E3754 72FE41B2 7DF8EBFC 365575D0
			1E9D4BF4 F53E6F3B 69DCB439 27CCE5C7
		</Data>
	</Key>
</KeyFile>`

From KeePass Website [KeePass Master Key](https://keepass.info/help/base/keys.html):

> XML (recommended, default). There is an XML format for key files. KeePass 2.x uses this format by default, i.e. when creating a key file in the master key dialog, an XML key file is created. The syntax and the semantics of the XML format allow to detect certain corruptions (especially such caused by faulty hardware or transfer problems), and a hash (in XML key files version 2.0 or higher) allows to verify the integrity of the key. This format is resistant to most encoding and new-line character changes (which is useful for instance when the user is opening and saving the key file or when transferring it from/to a server). Such a key file can be printed (as a backup on paper), and comments can be added in the file (with the usual XML syntax: ). It is the most flexible format; new features can be added easily in the future.

**Comment by PhilippC** [comment]
this is implemented in 1.08d-r3+: https://play.google.com/apps/testing/keepass2android.keepass2android

**Comment by ulfkosack** [comment]
Thanks @PhilippC. Works perfectly.
