### ISSUE TITLE
App crashes on android 4.4 KitKat

### ISSUE THREAD

**Issue by DamienSn** [PhilippC/keepass2android#1588]
When I open the app on my phone that is on android 4.4.4 KitKat, app crashes at start up. I have the error message "Keepass2Android has stopped". It may be very good if you could fix this bug.

**Comment by davidpierson** [comment]
I happen to have an old Galaxy S3 that runs 4.4.4 so I tried installing K2PA, to test, specifically for this trouble report.
I see app crash on app start, Exception class name = org.xmlpull.v1.XmlPullParserException
in source file Drawable.Java

createFromXmlInner

line number 986

The error does not concern me, because I don't use this old phone for anything except as a music player nowadays.  But perhaps the diagnostic is useful.

**Comment by PhilippC** [comment]
please install 1.07 from https://github.com/PhilippC/keepass2android/releases

**Comment by clst** [comment]
I can confirm 1.07 works. Are there plans to fix the Play Store version?
It was quite inconvenient having no access to my passwords after it automatically updated.
Also without a backup or root access the database would have been lost.

**Comment by DamienSn** [comment]
You can disable auto-updates in play store settings
