### ISSUE TITLE
Unable to save database

### ISSUE THREAD

**Issue by jochenpeters** [PhilippC/keepass2android#1592]
I don't find any kdbx files on my Samsung device.

Trying to export an open database from keepass2android (from Settings > Database settings),
it opens an "Android Datei-Browser" which then opens a dialog to unlock the database (which
was unlocked before) - and I am back where I started. No export.

Under "Open another database", I find dkbx files that I had imported - but none of them exists any more.

**Comment by PhilippC** [comment]
did you try to enter a new filename in the Android file browser?

**Comment by jochenpeters** [comment]
That's the crazy thing - or I am crazy: after selecting storange gtype (*.kdbx), I get a (blue framed) white panel with 1 icon that says Android-Dateibrowser (German device). Tapping on that icon, I am sent "back" to "Datenbank entsperren" (or "Wechseln") and there is nothing to specify the storage location / file name.
Am I missing something ?

**Comment by jochenpeters** [comment]
PS: I have version 1.08c-r1

**Comment by PhilippC** [comment]
this clearly does not sound like it should be. Could you please try if the same happens with 1.09a-pre1 from https://play.google.com/apps/testing/keepass2android.keepass2android? (This is the "non-offline" version - use a testing database if you don't want to use it with your real database)

**Comment by sedgemon** [comment]
Hi, Phillip, I am having a related problem and could use some help. I updated to the latest version of KeePass2Android from Google Play Store 2 days ago. With the previous version, I got a finger print login screen. This version wants me select the storage type. I store my PWs only on my phone, and don't have a cloud backup. I have searched for KeePass and *.kdbx on my phone's internal storage and find nothing.

I do find KeePass when I launch the app and do the following but I find no files .kdbx.  
>Open file system file picker
>Search for keepass - Phone finds keepass2.android.keepass2android folder
>Select keepass2.android.keepass2android folder 
>Select files subfolder - Files subfolder is empty

I have not tried to download the app you recommended in the previous message because I don't want to accidently write over or lose my *.kdbx file if it still exists.

My situation is not completely hopeless because I have a PW backup since I enter PW data periodically to KeePass on my computer. I could import that .kdbx file if needed. 

I would appreciate any ideas you have.

**Comment by jochenpeters** [comment]
Hallo Philipp (ich vermute, Deutsch ist OK),

ich bin neu auf github unterwegs und hoffe, diese Antwort erreicht Dich ohne Eintraege in github ?

Nachdem  sedgemon heute auch aehnliche Probleme berichtet, noch einmal hier nachgefragt:


  1.  Er findet keine kdbx Files auf seinem Device, ich bei mir (ueber Total Commander) auch nicht.
Kann es sein, dass keepass2android die geloescht hat ?
Ich kann mich nicht erinnern, selbt etwas geloescht zu haben ...

  2.  Ich erinnere mich, dass ich am Anfang verwirrt war, wenn ich dasselbe file.kdbx nochmal geoeffnet habe,
dass dann in keepass2android immer eine "neue" Datenbank wie file2 oder file3 angelegt wurde.
Gespeichert aus keepass2android heraus habe ich nie etwas (was ja nun leider fehlschlaegt).

  3.  Da meine Datenbank auf dem Samsung Smartphone inzwischen von der initialen Version auf dem PC
abweicht, habe ich Angst (auch wegen der Verwirrung bei 2.) etwas zu verlieren, wenn ich eine neue
Datenbank zum Testen mit dem pre-Release beginne. Ich habe auch nicht versucht, bei "Datenbank wechseln"
einen alten Eintrag zu laden (den ich wie gesagt ueber Total Commander auch nicht mehr finden kann).

Hast Du eine Idee, wie ich aus dem gefeuhlt "instabilen" Zustand am besten herauskomme, ohne Daten zu verlieren ?

Noch eine Anmerkung: Ich habe keepass2android in Samsungs "Sicherem Ordner" oder wie das heisst installiert
und die Datenbank auch dort damals hin verschoben, bevor ich sie zum ersten Mal geladen habe. Ob es damals
dann auch Dateien wie file2.kdbx oder file3.kdbx (siehe Punkt 2.) gab, weiss ich nicht mehr.
Jetzt ist dort wie gesagt (im "Sicheren Ordner") nichts mehr mit Suffix .kdbx zu finden.

Sorry fuer die Komplikationen - und danke fuer Hilfe :-)

                Jochen Peters

**Comment by PhilippC** [comment]
Hi @jochenpeters ,
replying to Github mails create a post on Github, so I'll reply in English.
Can you please specify which app variant (green/blue icon?) you are using and which version?

The app does not delete any files, but moving to Secure folder might cause some trouble - I don't know what that does exactly, but it's certainly not tested by me.

Can you give the beta version a try as suggested above?

**Comment by sedgemon** [comment]
Hi, PhillipC, 

Did you see my post above, and can you advise how to proceed? 

Let me know if I need to open a new issue?

Since my first post, I tried to access the "non-offline" version at https://play.google.com/apps/testing/keepass2android.keepass2android. Here is a screenshot of the message I see when I select the link but have received no update the app. 

![Testing Program Message](https://user-images.githubusercontent.com/79958787/109918323-96e70700-7c6b-11eb-89ff-a730b35fa14a.png)

What should I do now?

Sandi

**Comment by sedgemon** [comment]
I was able to update the to the non-offline version, but it still won't find the .kdbx file using file the System File Picker or Get From options. Now what?

**Comment by jochenpeters** [comment]
Hi Philipp,

I am using the blue offline version. You write that your beta link is a "non-offline" version.
What will happen when I click on "Tester werden" ?
Will it install the "green" app besides the blue "offline" version that I have - or will that disappear ?

Since I have no kdbx files on my device, how would I open my existing database ?

Sorry & thanks

Jochen

**Comment by sedgemon** [comment]
Phillip, I was able to upload a backup *.kdbx file, and the app works now.

I know technological glitches happen, but it was very frustrating that I updated the app and the *.kdbx file on my phone was nowhere to be found afterwards. Looking at the Google Play Store reviews, it seems there have been a lot of issues with the app, the latest Android update, and/or Samsung phones.

I've been a user and fan of KeePass2Android for years and never had a problem until now, so I'm going to stick with it. I wish you the best in resolving the issues. And I'll buy you beer because it's the right thing to do rather than continue to be a free loader.

Sandi

**Comment by jochenpeters** [comment]
Hi Philipp,

can you briefly explain the difference between the green/blue or offline/non-offline version ?
I don't want any internet connections/backups - is green then an option or should I stick to blue ?
If green: do I need to install it prior to getting your test version ?

Would that one find any possibly hidden databases from my blue version - even if my Total Commander doesn't find them ?

Thanks, Jochen

**Comment by PhilippC** [comment]
@sedgemon this appears to be a different problem, please create a new issue.

@jochenpeters the non-offline variant has more options how to open a file (i.e. it can access files through WebDav etc.), but you don't need to use them. The "advantage" of the offline variant is that it does not require network access permissions, so users don't need to trust me that I'm not stealing their passwords.

**Comment by jochenpeters** [comment]
Hi Philipp,
I always try to stay as minimal as possible. Not that I wouldn't trust you but if I don't need features, I tend to install the simpler version. Would it be easy to add the testwise improvements also to the blue offline version ? Would that then re-use the data of my currrent 1.08c version ?
Sorry & thanks
Jochen

**Comment by jochenpeters** [comment]
Good news (but strange):

After some app updates (but not for Keepass) on my Samsung device, saving now works, i.e., the file manager lets me select a destination file and really writes it :-)

I still have version 1.08c of the blue offline version.

Sorry for the trouble.

**Comment by PhilippC** [comment]
glad to hear that!
