### ISSUE TITLE
[FEATURE REQUEST] Option to copy/move entries and paste them in different directories

### ISSUE THREAD

**Issue by engineer22** [PhilippC/keepass2android#1600]
It would be useful to add an option to copy or move entries in different directories, and sort manually the entries from top to bottom.

Right now if I tap on copy entry, it will just duplicate it. This is not great, an option to copy the entry and then paste it in a new directory made inside the same DB, or move it entirely for example would be very useful.

The option to manually sort the entries also, would be useful too.

**Comment by LuckyStiff63** [comment]
I came here today looking for info on this exact topic.  I was hoping there was an existing way to move entries between groups, and maybe even move one group to be a sub-group under another.   

I can do these easily in KeePass2 on Windows, but I'm a non-programmer, so I'm not sure how difficult it would be to implement on Android?

**Comment by PhilippC** [comment]
If you long-tap an entry you can select the Scissors icon (Move entry), navigate to the target folder and then click the "Insert entry here" button.

Sorting is a different issue, it might exist here already. If not, please open a new one.

**Comment by LuckyStiff63** [comment]
Thanks for the info.   I remember using that method in the past, but it wasn't working for me yesterday (even after restarting my phone and KP2A), so I thought there may have been a change since I last used that function.

After reading your response, I cleared my KP2A cache, then restarted my phone, and all seems to be working again.

Thank you, and the whole team for all your effort in updating and improving this app, and for answering requests so quickly!
