### ISSUE TITLE
Password remains unencrypted in clipboard

### ISSUE THREAD

**Issue by Ottonormalverbraucher** [PhilippC/keepass2android#1618]
Hello, 
I am new here and not quite sure wether this issue realy has not shown up yet or if I do something completely wrong.
When I open keepsss2 on my Samsung wih Android 10 I am offered two choice what to do with my stored password. Show or copy to clipboard. As I have not easy to remember passwords I copy them to the clipboard. But there they are visible even days later, unencrypted and accessable for all other Apps. This is also valid when using Keepass2Andriod Keyboard.
So is the only chance to securely transfer the password from keepass2 to the requesting app to remember it and type by hand (with  Keepass2Andriod keyboard)?

**Comment by ei-ke** [comment]
Hello Otto,

that's due to Samsungs clipboard manager storing a history of everything you copied to your clipboard. As I find this behavior really annoying I just removed it from my device:
```
adb shell pm uninstall --user 0 com.samsung.clipboardsaveservice
adb shell pm uninstall --user 0 com.samsung.android.clipboarduiservice
adb shell pm uninstall --user 0 com.samsung.android.app.clipboardedge
```
[Source](https://blog.thul.org/technik/betriebssysteme/samsung-galaxy-tab-s5e-entruempeln/)

> So is the only chance to securely transfer the password from keepass2 to the requesting app to remember it and type by hand (with Keepass2Andriod keyboard)?

Of course not. Open the password entry you want to use in K2A. Go to the form or whereever you want to enter the username and/or password. When you are in any kind of text field and you have switched your keyboard to the K2A one you should see buttons to enter the username, password, URL etc. into the text field. This is done directly by K2A and thus the values are not captured by Samsungs clipboard service.

It would be even easier when you'd start using [K2A keyboard swap plugin](https://play.google.com/store/apps/details?id=keepass2android.plugin.keyboardswap2), but it needs to be enabled using ADB.

Cheers,
Eike

**Comment by Ottonormalverbraucher** [comment]
Thanks a lot for your help and explanation!

Stay safe!

Eike ***@***.***> schrieb am Di., 23. März 2021, 19:22:
