### ISSUE TITLE
How ot access log files on android?

### ISSUE THREAD

**Issue by modness-C137** [PhilippC/keepass2android#1728]
Hi all,

I have been using Keepass2Android for quite some time and ported my data to a new phone (S8 -> S21+) via Samsung's transfer tool. Now I'm experiencing peculiar behavior. The app is being closed randomly (it seems). To investigate why this is happening, I would like to access the app's logs, but can't find them.

Could someone help me out and tell me where to find the file and what editor best to use?

Thanks in advance

modness

**Comment by PhilippC** [comment]
you can go to settings - app - log file to enable and later "send" the file (when you select Send it will ask you which app to use. you can read instead of send the log then.)
Unfortunately, when it crashes, it will most likely not help to check the internal log. You might have to collect a logcat using the Android SDK tools then.
