### ISSUE TITLE
Close app button does not clear clipboard

### ISSUE THREAD

**Issue by FireEmerald** [PhilippC/keepass2android#1785]
The clipboard (current entry only) should be cleared or at least overwritten when the app is explicitly closed via the lock icon in the upper right corner.

I know that the clipboard may be device depending **but** when i click on the button inside the app it should be possible to overwrite at least the current entry.

This worked on my device just fine (One Plus 8) a couple of updates before but i don't know since when it stopped working.

**Comment by PhilippC** [comment]
As the documentation states, please do not use the clipboard for sensitive information. It is insecure, no matter what the app tries to do.

**Comment by FireEmerald** [comment]
@PhilippC Is there any other way to get complex passwords from within the app to another? I think there is no way. This means that most people will in fact use the clipboard to copy their passwords from A to B.

There is absolutely **no reason** to not overwrite at least the current content of the clipboard on app close.

Please explain why you do not want this behaviour. To say the clipboard is insecure anyways is not a good reason as this feature would at least improve the security of the clipboard a bit.

**Comment by PhilippC** [comment]
there is the built-in keyboard and the Autofill service. Both are secure and convenient. I have received too many requests from users complaining that clearing the clipboard dosen't work on their device. And even if it works, any app could have captured the password while it was in the clipboard. I keep the current functionality (because I learned that users kill me if I remove existing features), but won't extend it. 

please see https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md

**Comment by FireEmerald** [comment]
> (...) because I learned that users kill me if I remove existing features (...)

Well, you may noticed that i mentioned that when i clicked on the lock icon inside the app in earlier versions, keepass overwrote the current clipboard entry. Now it doesn't do this anymore. So this is no new feature it existed already and was removed?

**Comment by PhilippC** [comment]
I'm quite sure this is related to a change e.g. in your system. I didn't change this in the app.

**Comment by FireEmerald** [comment]
Okay, that's what i wanted to know. Seems like the clipboard is a strange thing in android 😅
