### ISSUE TITLE
Where do I create/get the OTP auxiliary file (for Yubikey)

### ISSUE THREAD

**Issue by MihaMarkic** [PhilippC/keepass2android#1876]
After reading [How to use Keepass2Android with YubiKey NEO](https://github.com/PhilippC/keepass2android/blob/master/docs/How-to-use-Keepass2Android-with-YubiKey-NEO.md) I'm scratching my head where do I get the OTP auxiliary file for using HMAC-SHA1 Challenge-Response? Using Yubikey 5 NFC.

I'd prefer this over HMAC-SHA1 over OATH-HOTP but I guess the same question apply for the later.

**Comment by PhilippC** [comment]
you need to setup the database in KeePass2 on Windows as explained on https://support.yubico.com/hc/en-us/articles/360013779759-Using-Your-YubiKey-with-KeePass

**Comment by MaShoGit** [comment]
Hi!

I¨ve installed KeePass 2, following the  guide at [https://support.yubico.com/hc/en-us/articles/360013779759-Using-Your-YubiKey-with-KeePass](url) mentioned above, and very good it is too.

To quote: "**HMAC-SHA1 is recommended** over OATH-HOTP because of its ease-of-use, as well as its ability to be backed up (it is not possible to have a **backup YubiKey** when OATH-HOTP is used).

Regrettably, I'm having difficulty in knowing which files, apart from the database file, to move to Android.

Candidates are:
  KeeChallenge.dll.config
  KeePassMasterallt.oxps
  NameDatabase.xml 
  
Surely, easy when you know how, but otherwise frustrating.
