### ISSUE TITLE
autofill notification disappears

### ISSUE THREAD

**Issue by jeroen7s** [PhilippC/keepass2android#19]
when i type a key on my keyboard (swiftkey in my example), regardless of key, including backspace and then slide down the notification tray with the autfill notification, it disappears, untill i leave the app and then open it again, then the autofill notification appears again

**Comment by PhilippC** [comment]
can you create a logcat of this please?

**Comment by jeroen7s** [comment]
logcat for KP2AAF: https://gist.github.com/jeroen7s/913e01e0463cdfdf587df9335a76073d
also been able to reproduce the other issue from notification tray.
the app i'm trying to login to is com.facebook.katana
it seems like it sometimes also detects com.touchtype.swiftkey
however what's more concerning is that it seems to detect:
com.snapchat.android
io.friendly
com.google.android.calendar
these apps weren't opened while i was logging, however, had notifications active in the notification tray.

**Comment by PhilippC** [comment]
Thanks for the log! I don't really understand why these events pop up, but it's interesting that the root element's package name actually is com.android.systemui (can be seen from the URL=..):
```

[ 10-03 10:20:52.544  2949: 2949 D/KP2AAF   ] OnAccEvent
[ 10-03 10:20:52.544  2949: 2949 D/KP2AAF   ] event: 2048, package = com.google.android.calendar
[ 10-03 10:20:52.544  2949: 2949 D/KP2AAF   ] no com.android.systemui
[ 10-03 10:20:52.723  2949: 2949 D/KP2AAF   ] URL=androidapp://com.android.systemui
[ 10-03 10:20:52.725  2949: 2949 D/KP2AAF   ] Cancel notif

```

However, this seems to be different from the swiftkey events. From the logcat I don't see that these should cancel the notification:

[ 10-03 10:22:10.156  2949: 2949 D/KP2AAF   ] OnAccEvent
[ 10-03 10:22:10.156  2949: 2949 D/KP2AAF   ] event: 32, package = com.touchtype.swiftkey
[ 10-03 10:22:10.156  2949: 2949 D/KP2AAF   ] no com.android.systemui
[ 10-03 10:22:10.254  2949: 2949 D/KP2AAF   ] OnAccEvent

This means that the event is not discarded as a notification drawer event (which is correct), but it also neither cancels the notification (there is no Cancel Notif) nor does it update it in any way, so that looks ok. Maybe you can create a shorter log with only few accessibility events, focusing on the swiftkey issue?

**Comment by PhilippC** [comment]
@jeroen7s  can you please check wtih the 1.02-pre4 which I uploaded to beta channel yesterday?

**Comment by jeroen7s** [comment]
it does seem like the notification stays now, thanks a lot, i think the swiftkey issue must have been related, since that's also resolved (opening keyboard adds a notification to the notification tray, that may have triggered the issue)
