### ISSUE TITLE
Delete database from the open list

### ISSUE THREAD

**Issue by Suncatcher** [PhilippC/keepass2android#1988]
How can I delete an old database from the list? I don't see any vertical dots, nothing. Tap on the database just opens it, nothing more

![IMG_20220510_093332](https://user-images.githubusercontent.com/6388034/167563825-ffe13be0-1db9-456d-8c2f-e44bd1e8caf9.jpg)

**Comment by Suncatcher** [comment]
uhm?

**Comment by PhilippC** [comment]
this is the list of currently open databases. You need to close (not only lock, but close) the database(s)

**Comment by Suncatcher** [comment]
Now I pressed "Open another database" and the first WebDav database disappeared from the list on its own, I didn't do anything.
The UI/UX is illogical and has no common sense. 

- When I want to delete the redundant database, I cannot, and it is not obvious why I cannot, it is not visible that both are opened. 
- When the first was closed from some reason (I didn't do this), it even disappeared from the recent list, which is not logical and not straightforward.

**Comment by mwmg** [comment]
I had troubles with this as well and also think that the UI could be a bit more intuitive, e.g. adding an option to close a database from the list of currently open databases would help a lot.

The steps I had to take were: entering the old database from the aforementioned list, clicking the lock symbol to lock it and only then being able to close it.
What complicated things for me, is that because I have biometrics enabled for QuickUnlock, after locking the database the biometrics prompt would immediately pop up, hiding the option to close the database (lower left corner). So it took me a few attempts to find out how to actually close a database.

**Comment by Suncatcher** [comment]
>> So it took me a few attempts to find out how to actually close a database

Absolutely. I was never able to find this close button when I needed it, and then it closed unattended, without my consent. Very non- intuitive and counter-productive UI.

**Comment by ilog2000** [comment]
I was also looking for remove/delete option, and also think that deletion of the local copy (and removing it from recently open list) must be in Settings explicitly. Imagine I decided to sell my used phone and want to clean up all personal stuff.

**Comment by briskshop** [comment]
Hi, 
I installed KeePassXC on different devices, now i want to avoid showing recent used databases from the list.
Does anybody found how to solve this issue reported?

**Comment by teicher** [comment]
I never found a "close button" but was able to close the old redudant database from the android notification, after locking it.
