### ISSUE TITLE
URL matching don't work on Android 12

### ISSUE THREAD

**Issue by xstable** [PhilippC/keepass2android#2039]
I've switched my device and from Android 9 to Android 12.
On both devices, I do use brave browser (fork of chromium)
At android 9 it work as expected, if I open the keepass-keyboard from a web formular... Means, keepass search for the url to find the credentials.

But on android 12, the reference is always the package name of the app: com.brave.browsee

![Screenshot_2022-07-27-19-41-02-916_keepass2android keepass2android](https://user-images.githubusercontent.com/1778068/181313634-d4496a55-1d21-4793-a6c5-0c3f11b79682.jpg)

How can I fix this?

**Comment by xstable** [comment]
I'd also give KeePassDX a try, with same result. As caused of this, I think it's an issue upcoming with Android 12?!

**Comment by Humpkes** [comment]
Hi,

I'm facing the same issue. It seems that KP2A on GrapheneOS is using the app name (Brave browser, “com.brave.browser”) instead of the webpage URL in combination with the KP2A-keyboard. With Firefox everything is working just right, NOT using the KP2A-keyboard; it just presents the autofill. Strangefully that's not the case with the Brave app; not autofill is shown. Anyone facing something similar or found a solution?

PS I did mention it on the [Brave forum](https://community.brave.com/t/autofill-not-working-reliably-with-bitwarden-or-keepass2android/70464/28) as a reply but no response.

Best regards,
Peter.

**Comment by WebworkrNet** [comment]
Related to  **Autofill does not recognise saved domain / URL #1755** .

**Comment by PhilippC** [comment]
@xstable did you try to use the Android Autofill service. This is the recommended way in recent Android versions? If you are you trying to fill with the keyboard, you should use the Share URL feature from the browser as described in https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md#browser-based-workflow
