### ISSUE TITLE
Keyfile on Android Cached?

### ISSUE THREAD

**Issue by anoderay** [PhilippC/keepass2android#2094]
I am using a Keyfile + Masterpassword for my database. After deletion of the keyfile from the phone I can still unlock the database without issue even though the app notifies me that it is unable to locate the keyfile.

Is this by design? I was under the impression that the keyfile would need to be locally present to work.

**Comment by r-clips** [comment]
I also just discovered this behaviour today.
I use a MasterPW together with a keyfile located on a USB flash drive.
I was amazed to find that subsequent attempts to open the database were successful even though the USB key was no longer present.
It appears that the issue can be circumvented/avoided by turning off the 'Database Caching' option.
This would seem to seriously compromise the security of using a keyfile as a second authentication factor, particularly since the 'Database Caching' option is set on by default when the App is first installed.

Surely this cannot be by design ......
It is not entirely clear to me why this caching is required. Can one assume that the cache is stored encrypted ?

**Comment by PhilippC** [comment]
it is by design, because you many users certainly wouldn't appreciate if thkey cannot access their data while being offline. Please disable file caching if you want to have different behavior.

**Comment by DiegoBM** [comment]
I think caching is a good idea as you mention for offline use. Maybe just make it visible (in case it isn't already) somewhere around the keyfile input that this behaviour will happen so that it doesn't come as a surprise for users that are not expecting it? Pointin out to the caching feature for people concerned about it.

P.S.: Thank you for this great app!
