### ISSUE TITLE
KeePass does not clear clipboard on exit.

### ISSUE THREAD

**Issue by osbope** [PhilippC/keepass2android#2210]
After copying a password from a keypass d/base entry to the clipboard for onpassing in a login sequence, the clipboard  retains the password, even after closing the KeePass d/base and exiting the KeePass application.
Any other android app is able to access the clipboard and plain text password.

**Comment by PhilippC** [comment]
that's why the app and its documentation state you shouldn't use the clipboard for sensitive content. There are better ways of transferring data out of the app. Android clipboard is insecure, nothing we can do something about.

**Comment by Propheticus** [comment]
You could flag it as sensitive data, to change the cleartext to dots.
https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#SensitiveContent

**Comment by AriehSchneier** [comment]
> https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#SensitiveContent

@Propheticus already done: #2106

**Comment by Propheticus** [comment]
> > You could flag it as sensitive data, to change the cleartext to dots.
> > https://developer.android.com/develop/ui/views/touch-and-input/copy-paste#SensitiveContent
> 
> @Propheticus already done: #2106

Does not seem to work. I see clear text passwords in the clipboard / paste suggestion.
I'm on Android 14/OneUI6.0 on Samsung A53. So is Samsung to blame here for not implementing this feature?
Pretty big security risk, since the Samsung keyboard also stores clipboard history which the 'clipboard timeout' is unable to delete (have it set to 1min).

I understand it's better NOT to use the clipboard function at all, but sometimes you need a fallback for when autotype does not recognise fields/fails to enter in the right field.

Would it not be safer to copy an autotyping 'intent' referencing the specific object's (database entry) password? Pasting this intent would then call keepass2android (K2A) with an URI pointing to a specific password, after which K2A then can do authentication if needed or when still unlocked continue with autotyping in the currently selected field you pasted the intent in.

The upside being you never store the actual password in the clipboard. If another app/malware accesses you clipboard history and calls the old intent you would get a suspicious launch and authentication request from K2A while you did not initiate anything. When cancelling the request, no data is leaked. 
Going further you could generate temporary URIs in such a way they contain a randomised ID which become invalid after x minutes.  Either a lookup entry to the actual item stored within the app / or pointing to a temporary object that is a copy of the password which gets deleted after a minute.
