### ISSUE TITLE
Android file system and KP aren't seeing kdbx file

### ISSUE THREAD

**Issue by ithinktfiam** [PhilippC/keepass2android#2280]
Old Android died, bought new. Copied files onto the new. Kdbx is in Documents, but when I try to open it, KPAndroid doesn't see it. Went to the file system and it is only showing pdfs in that directory. I see the file through File Explorer when connected to my laptop.

Why isn't the system or the app seeing the data file and how do I fix that?

**Comment by PhilippC** [comment]
can you check with the "Files" app on the mobile? Do you see it there?

**Comment by nutpantz** [comment]
I could be wrong but some newer Android versions 12 13+  only show media files like jpg ,pdf etc before l because it only has media permission. It might need all files permission (or whatever it is called). I ran into this issue with a ftp app i had not updated with my pixel 6 Android 12
But it's not universal since a custom ROM Android 12 on my s7 had no issues.
Check to see if you can give it the "all files"permission

**Comment by ithinktfiam** [comment]
Sorry, forgot to reply. Was traveling and in a crunch. Got home and had more time. What you said was right. I downloaded four different file managers. Two didn't see the file and two did. Joy...

Anyway, was able to see the file and manage it. Thanks for the response.
