### ISSUE TITLE
Feature Request: Disable donation reminders for GitHub sponsors

### ISSUE THREAD

**Issue by robellegate** [PhilippC/keepass2android#2291]
Hello @PhilippC,

[As a proud sponsor of your project through GitHub Sponsorships](https://github.com/robellegate?tab=sponsoring), I'm writing to suggest a feature that I believe would improve the user experience for sponsors like me.

Would it be possible to add an option for GitHub sponsors to disable in-app donation reminders? As someone who supports the project financially, I'm already doing my part and would prefer not to see these reminders. I believe this feature would be greatly appreciated by other GitHub sponsors as well.

To implement this feature, you could add a toggle switch in the settings menu labeled "Disable Donation Reminders for Sponsors." This option would only be visible to GitHub sponsors who have [authenticated to the app via device flow](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-user-access-token-for-a-github-app#using-the-device-flow-to-generate-a-user-access-token), and selecting it would prevent any in-app donation reminders from appearing.

Thank you for considering my request, and for all the hard work you've put into this project.

Best regards,
Robert

**Comment by PhilippC** [comment]
Thanks a lot for sponsoring! This is really appreciated and keeps me believing that it's worth to spend hours and hours simply for answering support requests and trying to keep the app running while the ecosystem evolves...

Did you notice that there is already an option to disable the donation button? It gets activated after using the app for a while. It is available for everybody (because I consider a donation as something you don't get any benefit for "personally" and because I wanted to keep it simple). If that option is enough, feel free to close this. If it is not, let's keep it open.

**Comment by robellegate** [comment]
Ah, I wasn't aware of that setting. Thank you for your response and continued work on this project!
