### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by githububdata** [PhilippC/keepass2android#2429]
Windows Keepass 2.44
Android 1.09e-r7
I'm trying since long time to enable a stabile sync in both directions via dropbox. However, once a year I usually have to synchronize about 20 corrupted copies. I believe I've tested all possible options, but maybe you have any hints or guidance for me?
Thx
Ulf

**Comment by PhilippC** [comment]
I suppose instead of "corrupted" you mean "conflicted" copies? This should not happen when you use KP2A's built-in dropbox support (Open file > Dropbox). If the conflicts are caused on the PC side, please check the options you have there, e.g. https://keepass.info/help/kb/trigger_examples.html#dbsync.
