### ISSUE TITLE
[QUESTION] Auto fill username and password

### ISSUE THREAD

**Issue by zuku81** [PhilippC/keepass2android#2506]
Hello,
Keepass2android version 1.09e-r7
Android version: 14
How to configure autofill feature when username and password is required in application? When I click autofill during an sign in on my android application and choose keepass2android to fill these data, then it fills on username and password fields only password twice.

Unfortunately send debug log in application do not work(it do nothing).

**Comment by zuku81** [comment]
Hi,
This is Citibank mobile application:
https://play.google.com/store/apps/details?id=com.konylabs.cbplpat

**Comment by PhilippC** [comment]
This must be fixed in the Citibank app: Android passes the "autofill structure" to Keepass2Android. There are clearly two fields with attributes indicating that both are password fields. I can see this when querying the https://developer.android.com/reference/android/app/assist/AssistStructure.ViewNode#getAutofillHints() method and when looking at view node's input type. 
I suspect they wanted to "protect" both fields in a weird way which makes the username look like a password.
