### ISSUE TITLE
How to disable autofill on Oreo?

### ISSUE THREAD

**Issue by psycholyzern** [PhilippC/keepass2android#253]
The autofill button appear in text editor covering menus.

OnePlus5T Android 8.0.1

**Comment by PhilippC** [comment]
can you please post a screenshot to clarify what you mean? You can disable auto fill by going to the system settings, search for autofill and set to none.

**Comment by psycholyzern** [comment]
Thanks. That is what I was searching for. I thought the setting was in the app itself, turned out in system settings.

**Comment by jmevel** [comment]
Hello, 
I honestly don't know how you properly disable AutoFill.
I went to the Application Settings -> Password entry access
I saw the "button" where it's written "AutoFill Service enabled"

Kept clicking on the button and also tried long press but absolutely nothing happened. After 15 minutes looking everywhere and searching for help on the web I finally decided to uninstall and re-install the app.

So what's going on? How to properly disable AutoFill, because the settings I went to don't work.

Thanks you

**Comment by psycholyzern** [comment]
You should go to system settings, not to app settings. My autofill setting is located under Languages & input. Yours might be different. You can easily search for it by typing "autofill" in the search bar.

![screenshot_20180901-160817](https://user-images.githubusercontent.com/5763466/44943954-9141a980-ae01-11e8-9779-5348c4637303.jpg)

**Comment by PhilippC** [comment]
this required a somewhat hacky trick to show the settings even if KP2A is Autofill, but is now implemented.
