### ISSUE TITLE
Why did I get a not fully tested version update?

### ISSUE THREAD

**Issue by hmvago** [PhilippC/keepass2android#2537]
Dear Sirs,
recently I updated all my Android applications in my cell phone from the Google Android Store.
Afterward, I realized that my Keepsass2android version has been updated to a not fully tested version ( Version: **1.10-pre**). **This was not what I wanted to do**.
Why is this happening? My first aim was to have a better and more secure version.

This said, I want to **thank you all very much for this excellent, Open and Free application**.

Best regards.
Hernan Vago

Now, my App version is:
App: Keepsass2android
Version: 1.10-pre
https://play.google.com/store/apps/details?id=keepass2android.keepass2android_nonet&gl=us

**Comment by hmvago** [comment]
If I want to roll back or install the last stable release how should I proceed?
Thank you very much.

Hernan Vago

**Comment by PhilippC** [comment]
1.10-pre was marked as "pre-release" when it was built, but then turned out to be fully stable so it was released to the production channel. There is no reason to roll-back. If you want to do so anyway, make sure to create a copy of your database (verify you can open it on a separate device), then uninstall the app and install an older release from https://github.com/PhilippC/keepass2android/releases
