### ISSUE TITLE
Key file not used

### ISSUE THREAD

**Issue by Caplande** [PhilippC/keepass2android#299]
Hello,
My keepass db (kdbx) is stored in dropbox. From my PC windows10, I open this db with password + keyfile.
I installed Keepass 2 android in my tablet. At the first time, I need password and keyfile to open db, and in the following next open sessions, the only password is enough (I disconnect usb key which contains key file). I specify that I take the precaution of closing the database each time. 
My question: Is it a mishandling on my part or a bug of application (cache issue ? )?
Thank you for your help.
Caplande

**Comment by tarminu** [comment]
Did KP2A copy the key file to its internal directory?
Check Settings -> Database; at the bottom
Is "Import key file to internal folder" greyed out with a message that "File is stored in internal directory"?  If so, that's why you can open the DB without the key file on a USB drive.  You can control this behavior in Settings -> Application -> Security -> Save key file.

**Comment by PhilippC** [comment]
This is related to the "database caching" settings (app settings / file handling / database caching).   This setting is also used when accessing key files, i.e. the key file might be in the app cache. If you disable db caching, the key file will not be stored in cache anymore (but the database is not, either, so you cannot access the database without internet connection).
