### ISSUE TITLE
How to disable keepass2android for certain fields

### ISSUE THREAD

**Issue by lkesteloot** [PhilippC/keepass2android#303]
I'm not a user of keepass2android, I'm a developer of another app. One of my users is complaining that keepass2android is repeatedly suggesting auto-fill for fields where it makes no sense, for example when adding an item to a shopping list:

![image](https://user-images.githubusercontent.com/419771/37547038-b6284718-292c-11e8-9b3b-71bf44b9b63d.png)

and:

![image](https://user-images.githubusercontent.com/419771/37547043-ba40d8a6-292c-11e8-8ef5-3bc751ab4933.png)

The users says: "The android app views the find or add item field as a password field and prompts me to autofill with my password manager. Additionally, when I submit, the manager asks if I want to save my password, which I obviously do not. It's not the worst issue in the world but would greatly appreciate if the field type was changed so that autofill didn't see it as a password field."

Here's the field from the screenshot:

        <EditText
            android:layout_height="wrap_content"
            android:lines="1"
            android:layout_width="wrap_content"
            android:hint="@string/add_item.ItemNameHint"
            android:id="@+id/add_item.ItemName"
            android:inputType="text|textFilter"
            android:layout_weight="1"
            android:layout_marginTop="2dp"
            android:imeActionLabel="@string/add_item.KeyboardAction"
            android:imeOptions="actionNone|flagNoExtractUi"
            />

I don't see anything here that would cause it to be detected as a password field. I've looked through other issues and through the documentation folder and didn't see any advice to developers of other apps for how to avoid this problem.

**Comment by max-frank** [comment]
Additional info, this is seems to be a general issue. The same thing happens for the Google translate app (v5.17). 

Specifically autofill prompt shows when entering something and the password save prompt shows after submitting.

**Comment by lkesteloot** [comment]
@PhilippC https://play.google.com/store/apps/details?id=com.headcode.ourgroceries&hl=en

**Comment by PhilippC** [comment]
thanks. The input type which I get from the AssistStructure.ViewNode is 
`Android.Text.InputTypes.ClassText | Android.Text.InputTypes.DatetimeVariationDate | Android.Text.InputTypes.DatetimeVariationTime | Android.Text.InputTypes.TextVariationPassword` (using Xamarin constants). I will contact the Google Autofill team to see why this is happening.

**Comment by lkesteloot** [comment]
This is for the "Add an item" text input field? I've pasted above the XML for it. Here are the changes I make procedurally on that field:

        m_editText = (EditText) findViewById(R.id.add_item_ItemName);
        m_editText.addTextChangedListener(this);
        m_editText.setOnEditorActionListener(this);
        if (getCapitalizeItems()) {
            m_editText.setKeyListener(new TextKeyListener(
                        TextKeyListener.Capitalize.SENTENCES, false));
        }
        if (!getAddMultipleItemsPreference()) {
            // Show a Done button if we're doing single-item adding.
            int imeOptions = m_editText.getImeOptions();
            imeOptions = (imeOptions & ~EditorInfo.IME_MASK_ACTION) | EditorInfo.IME_ACTION_DONE;
            m_editText.setImeOptions(imeOptions);
        }

I don't think those changes should have the effect you're seeing.

**Comment by mydexterid** [comment]
Just FYI other apps have this issue too (that Xamarin sees TextVariationPassword field for some reason)
https://github.com/bitwarden/mobile/issues/57#issuecomment-347293272

**Comment by PhilippC** [comment]
thanks @mydexterid  for pointing to that link. By further research, I found https://bugzilla.xamarin.com/show_bug.cgi?id=59532 which seems to indicate that this bug is causing the KP2A behavior. However, it should be fixed already and I still see the behavior. Will look further on how to resolve the problem.

**Comment by PhilippC** [comment]
after quite some work of this, I have summarized my thoughts at https://stackoverflow.com/questions/49490222/android-api-constant-values-of-inputtype - if anybody can answer would be great.

**Comment by PhilippC** [comment]
found the bug and fixed it. Will try to publish an update in beta channel this week.

**Comment by lkesteloot** [comment]
Thank you!

**Comment by Yemono** [comment]
Still happening for me with Bacon Reader 5.4.1, Keepass2Android 1.04b. Android is at 8.0.0 (newest update by phone manufacturer).

**Comment by gpion** [comment]
Still facing this issue with current beta (1.06-pre1)
![screenshot](https://i.imgur.com/dao822I.png)

**Comment by PhilippC** [comment]
@gpion what app is this?

**Comment by gpion** [comment]
https://play.google.com/store/apps/details?id=ccc71.at

**Comment by PhilippC** [comment]
I just debugged into this. It's an issue with the 3C Toolbox app. That app "claims" the terminal field is a "visible password" (maybe to avoid showing autocompletion by the keyboard). Please contact their developers to fix this.

**Comment by gpion** [comment]
Ok for the terminal app since I just found a alternative app  providing the same feature and which doesn't have the issue: [JuiceSSH - SSH Client](https://play.google.com/store/apps/details?id=com.sonelli.juicessh)

But I keep getting the autofill prompt in others apps. 
That one for instance (same "visible password" explanation):
[Quoty](https://play.google.com/store/apps/details?id=com.agilys.moncaddy) 
![Quoty screenshot](https://i.imgur.com/S7TnfsL.png)

Also please note that when another autofill service (I've tested Google's and Samsung's, which come pre-installed on my phone) is selected, the autofill popup does not show up until having made a long press on the text fill and selected _"autofill"_ in the context menu.
![3C screenshot](https://i.imgur.com/vKd08SD.png)
This seem a perfectly usable behavior and could be an fine workaround (possibly optional: Keepass options -> _"do not  show autofill prompt until long press on text field and having selected corresponding menu item"_)) you may consider implementing.
That would also solve the Keepass Autofill prompt  which also pops up when were asked to type the pin code in some areas of Android Settings.
"Smart Lock" for instance:
![Smart Lockscreenshot](https://i.imgur.com/KMgP00R.png)
