### ISSUE TITLE
can't get rid of "Enable Autofill" message

### ISSUE THREAD

**Issue by tessus** [PhilippC/keepass2android#311]
When I open a database, there's a message at the bottom of the screen which I can't dismiss:

```
Keepass2Android supports Android's Autofill feature but
it looks like you haven't enabled it yet.

ENABLE AUTOFILL                        SHOW AUTOFILL HELP
```

This message takes about 1/6th of the screen and I know that I haven't enabled it - on purpose !!!
There's no way to click it away or tell the app not to show me this message.

It's ok to show me this message once (not every time when I open a database), but when I dismiss it, it should be gone for good. In any case, I can't even dismiss it in the first place. It's there permanently and it's very annoying (like an ad).

Any chance you could create a setting not to show this message?

**Comment by PhilippC** [comment]
it will disappear as soon as you enable autofill. Then return to the app which disables the message. Then disable autofill if you don't like it. The message won't appear again.

**Comment by rwese** [comment]
Do you mean this notification? @tessus 
I was wondering the same, I have enabled 'use keepass as password safe' on my Samsung Galaxy S8+ and now it popsup in weird places. The problem is I can't tell if Keepass2android is to blame or the PasswordSafe feature if the Samsung.

For example in BeaconReader I get the 'fill with keepass2android' popup when writing a comment, see ![screenshot](https://user-images.githubusercontent.com/7153716/37904455-1b1f28f4-30fc-11e8-8f7a-bbcc20df512c.png).

Just let me know where to put this issue, if anywhere at all. The old SamsungPass didn't popup in "wrong" places.
Cheers.

**Comment by PhilippC** [comment]
@rwese what you describe is issue #303

**Comment by tessus** [comment]
@PhilippC I just came back from vacation where I didn't have Internet (yeah, those places still exist ;-))

> it will disappear as soon as you enable autofill. Then return to the app which disables the message. Then disable autofill if you don't like it. The message won't appear again.

Ah, ok, since I never wanted to activate it in the first place, it never came to me that I should actually try it. Thanks for the info.

Also, thanks for 61ef383c38157bbc8aff1d82c37daec3bf06c72a

**Comment by tessus** [comment]
@PhilippC How do I deactivate AutoFill again? I can't seem to deactivate it. Now every time I get a popup in other apps whether or not I want to use Keepass2Android (to store the password to or use the password from). Or shall I open another issue?

**Comment by PhilippC** [comment]
you go to your system settings and search for auto-fill, there you can disable it.

**Comment by tessus** [comment]
Thank you very much, this did it.
