### ISSUE TITLE
Mobile data not in sync with desktop data using Google Drive

### ISSUE THREAD

**Issue by kewlguy2** [PhilippC/keepass2android#363]
my databases are no longer staying in sync using Google Drive on such a diverse group of devices & browsers.

The database, stored in my personal Drive, that my mobile uses is falling behind on changes made from desktops even if I completely log out of the current mobile app including locking the database.

I just opened my google drive database on both Ubuntu and Windows and there is the entry I am looking for yet it refuses to sync up fully to give me the entry on both of my Android mobiles.

I have current pictures you can see in that the folder & entry are missing on my mobile(s) from an entry that was saved on my Windows desktop that my Ubuntu machine can see using the same Drive storage.

**Comment by freMea** [comment]
Same issue here with v1.04b on Android 6.0.1

It used to work. 

For testing, I created a new entry in K2A. Then I ran a sync into K2A. It reported my files were synced but when I go to gDrive, my kdbx file was not updated and Keepass doesn't see changes.

The sync feature keeps working in Keepass 2.38 on my Windows, it modifies the gDrive file when I run the sync. But now my mobile DB and desktop DB are out of sync since K2A fails to upload changes to gDrive despite it says it's OK.

The K2A log doesn't show issues about sync. [Here](https://paste.ubuntu.com/p/pQ2Y4zgxRN/) it is.

**Comment by freMea** [comment]
It seems I solve the issue.

## Steps

_Before sync from both side, check the file modification date in GDrive is the last one._

1. Close DB from K2A
2. Long press the one in recent file and delete
3. Open the GDrive DB with K2A assistant

It seems the sync feature works as expected now.

**Comment by Karreg** [comment]
I have the same issue, but for me is related to google drive and how the desktop version works.
To avoid it, I use a master file, used by my several Keepass2Android, since synchronization is standard.
Then I use a separate file on desktop, one for for each different computer, that I manually synchronize with the master file.
To avoid still further issues, I disable google drive sync when doing so...

**Comment by PhilippC** [comment]
might be related to https://github.com/PhilippC/keepass2android/issues/165

**Comment by kathyw2** [comment]
Have the same issue.  Android and Windows both indicate they are synching to Google drive, but the time stamp on the Google drive only shows the update when the Windows version syncs. This has been going on for a few months. Searching the Android drive doesn't show a local version on the phone. So, not sure where it is saving.
Now suddenly the Android version just flashes when trying to open, and goes back to the open file screen.  Is there any way of getting it back?

**Comment by kathyw2** [comment]
No longer being able to open might be related to https://github.com/bpellin/keepassdroid/issues/78 and https://github.com/bpellin/keepassdroid/issues/75
as I'm getting "This file type is unsupported" when opening kdbx via Google Drive on my Android.

**Comment by Kagami** [comment]
Having the same issue. K2A can't see updates of files on gdrive (I'm using rclone to update on PC side).

**Comment by Kagami** [comment]
I think I know what's the problem.
Seems like K2A uses gdrive's file IDs to access the database file and rclone creates new IDs every time so K2A can't access the old file.
[gdrive utility](https://github.com/prasmussen/gdrive) supports updating of file contents by ID and seems like it works now.
Though it's not that user-friendly compared to rclone FUSE mount.

**Comment by kewlguy2** [comment]
FYI I have issues where when I save new entries at my ubuntu laptop
computer then I save the database, using goigle-drive-ocamlfuse, to my
Google Drive folder then on my Android App I am informed that my database
is trashed yet when I skip the "recent" files & shop for the database by
re-adding it to Keepass2 my database is fine & has my updated entries.

Regards,

Don Moody
1(780)707-5558
www.handymanreality.com

NOTE: I discovered that the BEST place to put ratings for businesses where
one can be easily added, on mobile, is through the Google maps by entering
"Handyman Reality Edmonton" then touch the marker balloon and tapping on
the company listing to select a star rating/review.

just follow this link
https://goo.gl/maps/LLKGiCroQ1R2

**Comment by PhilippC** [comment]
@Kagami Google Drive does not really have the concept of file paths: There can be two files with the same path! So that is not an option, sorry. (That's my main reason I don't like the GDrive concept/API)

**Comment by braham-snyder** [comment]
I think I just lost all entries I added through K2A while it was in this de-synchronized state (which could have been a long time), since I removed and re-added the database to work around it without thinking about it enough.

Does the Google Drive API really send outdated files without notice? Is there maybe a way to automatically check if the file being sent is out of date, to at least give the user a warning so it can be backed up and manually merged?

It seems like if this were an rclone bug it would be pretty easy to find, but I don't see anything from a cursory search.
