### ISSUE TITLE
Key File

### ISSUE THREAD

**Issue by kwoodcock44** [PhilippC/keepass2android#364]
I've changed by master password, but unable to link to a key files again.  Went to settings, database settings, change master key. Enter new password and full path for keyfile but message just stays on the screen saying setting password. The file name is definitely correct. Any help would be welcome, thanks in advance. P.s Excellent app.

**Comment by PhilippC** [comment]
I agree that this dialog must be improved. For the time being, I think this looks like there is an error with the key file. I looked at the code and error handling is not correctly implemented there. Maybe you can update the keyfile on Windows with Keepass2?

**Comment by mnikulin** [comment]
i've used dropbox-like service as kdbx storage (can keep offline copy in Android/data/com.dropbox.android/files/u1234567/scratch/) and i had to copy key file only once on new Android device (by wire). I'm using one-way syncronisation and do all DB changes only on desktop, but since i start using yubikey and OTP on desktop only i need another kdbx to work on Android without OTP. When i change DB i can use same OTP codes on desktop and mobile (manually or may be even using yubikey via USB-host with some OTP look-ahead), but need some way to switch to old-fashion key file after opening this DB on mobile. So "Change Master Key" dialog works only without key file now :( Honestly i'm not sure that using key file matters when storing DB in such weird way, but i'd rather use key file than not.
**Please, fix this dialog or give some advice how to specify path to key file?!
thanks a lot**
P.S.
this issue seems dups #163 but i'm still think that creating old-fashion copy on desktop not suitable, for example because it needs syncing/coping DB again instead of just typing OTP.

**Comment by PhilippC** [comment]
@mnikulin Why don't you use YubiChallenge instead of OTP? You only need to copy the xml file along with the kdbx then. I don't think that a keyfile gives any benefit as it is located on the same storage as the kdbx. If you still want to do it, please create a kdbx file with keyfile on the PC and transfer both to the mobile.

**Comment by kwoodcock44** [comment]
Not sure if this helps at all but I keep the kdbx on onedrive or Google drive and the key file on the local device.
