### ISSUE TITLE
Doesn't work on ASUS Fiip Chromebook

### ISSUE THREAD

**Issue by yeswap** [PhilippC/keepass2android#422]
Om my ASUS C100PA Flip Chromebook, after I choose my database the KeePass2Android window becomes solid black with no way to proceed.
![Image of problem](https://3.bp.blogspot.com/-sAotrEHYv2k/Wy0c3Piw0MI/AAAAAAAAXm0/m2C5NxrifN47oo4wjVhlWVhIxtFmZfAuACLcBGAs/s640/Screenshot%2B2018-06-22%2Bat%2B8.48.13%2BAM.png)

**Comment by Yorik-Code** [comment]
Work in my Pixelbook. Maybe you could always
So provide what version your running. Also make sure that none of your extensions are causing the issue.

**Comment by yeswap** [comment]
Disabling all extensions did not fix it.
I'm using Chrome OS Version 66.0.3359.203 and Keepass2Android 1.04b

**Comment by pmarkkula** [comment]
Does this happen with chromebooks own display, or with external one? I reported this some time ago as bug to chromium developers, because I was seeing this with external display:

[https://bugs.chromium.org/p/chromium/issues/detail?id=791495](url)

Turned out that this is expected behaviour when application tells (uses FLAG_SECURE) that window can contain sensitive information.

**Comment by yeswap** [comment]
Thanks, you are right I just checked and the issue only occurs with my external monitor. 

I wonder if this app needs to use  FLAG_SECURE? That flag seems to be mainly intended to keep users from stealing DRM protected content by doing things like recording a Netflix movie on a DVR. 

Does FLAG_SECURE add any value to Keepass2Android? It doesn't seem like a physically attached external display is any riskier than the device's built in display.  Attaching a monitor requires physical access to the machine. If an attacker has physical access plus the device and keepass login credentials they don't need an external monitor to steal your passwords. Linux and Windows Keepass implementations work on external monitors.

**Comment by PhilippC** [comment]
FLAG_SECURE is required. It protects the screen contents in different ways, e.g. the task manager won't capture and display "screenshots". You can disable the usage of the flag in the app settings.

**Comment by yeswap** [comment]
Thanks, I just disabled the flag and bought you a beer. Thanks for a great app and great support.

**Comment by pmarkkula** [comment]
Would it be possible to show something else than black window? Something that would tell user what is going on.
And what about chromeboxes that don't have internal display at all?

**Comment by sourceomatic** [comment]
Not to threadjack, but I'm having this problem on a ZTE Blade V8 Pro cellphone running Android.  I can log into my DB manually, but as soon as I try to enter the settings screens, K2A (and also K2A Offline) throw me into an all-black screen.  Meaning, I can't get far enough to shut off the FLAG_SECURE setting!  Is there some way besides the app's UI where I can disable this setting?

**Comment by PhilippC** [comment]
@sourceomatic please collect a logcat if you can.

**Comment by sourceomatic** [comment]
Philipp, I'm currently coming back around to Android, after having not messed with it much for years.  But, I had used ADB back in the days around KitKat.  Unfortunately I don't have any of the SDK tools installed right now, but will see if I can get you something useful over the coming week or two.

Also, if you would prefer, I can start a new issue.  In the meantime, I will stick to this thread, unless you request I start my own.  Thank you!

**Comment by sourceomatic** [comment]
Hi again Philipp.  Well, this evening, I sat down to try to obtain a logcat for your review. 

Unfortunately, today was the day that ZTE's ban from the US Department of Commerce was lifted.  By the time I put myself on the task of relearning ADB, ZTE's update servers had come back online.  And of course, my phone updated its Android Build and Security patch level automatically (nice timing).

Naturally, that made the problem go away.  D'oh!  Uh, I mean, "Wahoo!"  No more crashes, everything works as expected.

So I guess it's a "good news, bad news" situation.  The problem is gone for me, but I regret I wasn't much help diagnosing the root cause.   I'm not a betting man, but if I were, I'd wager the fault was the old OS/patch levels, and NOT anything wrong with Keepass2Android itself.

**Comment by Skylled** [comment]
Oddly, Keepass2Android worked great on my (Lenovo Yoga C630) Chromebook for a long time, but has now decided to only show the black screen. I'm not sure whether its an issue with the device, a change to Chrome OS (currently running Canary), or a recent change to K2A.

If there's any info I can provide to help with debugging (I have adb enabled already, for example), let me know.

**Comment by Skylled** [comment]
Sorry to bump again. Two weeks later this has resolved itself, so it must be an issue on the Chrome OS side, not on KP2A's part.
