### ISSUE TITLE
Samsung compatibility

### ISSUE THREAD

**Issue by tijn210** [PhilippC/keepass2android#427]
Make it compatible with samsung internet browser

**Comment by tijn210** [comment]
I'm missing the compatibility for autofill in samsung browser

**Comment by PhilippC** [comment]
If you mean Oreo autofill, this is something that must be supported by Samsung. If you mean accessibility autofill, please see https://github.com/PhilippC/kp2a_accservice_autofill/

**Comment by Suncatcher** [comment]
I installed the plugin as per the recommendation but the autofill doesn't work in Samsung browser anyway. Why?

**Comment by Offerel** [comment]
@Suncatcher could you solve the issue with Samsung Internet? For me it's not working. Neither via accessibility, nor via Autofill plugin. Using KP2A 1.09pre and stable Samsung Internet.

**Comment by Suncatcher** [comment]
The same. I wasn't able to solve the issue, waiting for reply from @PhilippC

**Comment by PhilippC** [comment]
does any other password manager (e.g. Bitwarden) provide Autofill (through Android's Autofill framework, not Accessibility) in that browser?

**Comment by Offerel** [comment]
I'm since ages on the beta channel and 1.09a-pre1 is installed. So at least for me on a Samsung Galaxy S20 FE with standard german VDF ROM, Samsung Internet 13.2.2.4 isn't working. It's no big issue for me, since my standard browser is still Firefox, but from time to time, i have to use Samsung Internet. 

If you want, we can try to dig a little bit deeper here. You can't have every combination of app and phone for testing and if i can do something for you, please let me know.

I have tested Samsung Internet also with KeePassDX, with this, the Autofill is not working. I have no idea, what this app is using.

**Comment by PhilippC** [comment]
if you want Samsung Internet to support Autofill, then please file issues on the Samsung support page. I don't know how responsive they are, but there is an Android API for this which needs to be implemented by browsers and password managers. Keepass2Android has this implemented, if Samsung doesn't implement it for their browser, then it just can't work.

**Comment by Offerel** [comment]
Hi Philipp, do you have a link/Url for that page? Maybe, we can be successful together...
