### ISSUE TITLE
Backup storage place in Android

### ISSUE THREAD

**Issue by cynicotb** [PhilippC/keepass2android#447]
Can you please inform us where we can find the "local Backup" in Android 8.0.0?

Is it intended as a full blown backup that we can open,  in case of an emergency with the original database?

Same questions for the local cache copy...

Thanks for the wonderfull app!

**Comment by PhilippC** [comment]
the local backup is placed under the app's so called "NoBackupFilesDir" (an internal directory which is not backed up by Android/Google). 
File storage caching is stored in the App's cache directory. This is not ideal as this might be cleared by the Android OS if low on memory, which is why I might move this to NoBackupFilesDir in the future as well.

**Comment by cynicotb** [comment]
Dear PhilippC,

Thanks for your reply!

As I am a novice on Android, would you mind explaining the drive and path of the directories you mentioned: "App's cache directory" and "NoBackupFilesDir"?

Should they be visible and writeable in an 'explorer' on a non-rooted device?

Sincerely, Ton.

**Comment by PhilippC** [comment]
no, both are not.
