### ISSUE TITLE
Prevent users from accidentally opening the local backup

### ISSUE THREAD

**Issue by PhilippC** [PhilippC/keepass2android#479]
This happens too often. Better hide the local backups in the recent files list and add a checkbox to show them.

**Comment by tariksbl** [comment]
+1 , this puts the db in r/o mode & it's not clear why.

Also, disabling "database caching" and "local backups" doesnt seem to delete the local backups as the warning states, it's necessary to clear application data.  Also these settings need to be disabled in the process of reconfiguring your db since they're on by default.

Maybe prevent local backups if the db is on gdrive or box, instead suggest that the cloud provider's offline storage be used.
