### ISSUE TITLE
Unable to see keyboard autofill pop-up window

### ISSUE THREAD

**Issue by kevinzying** [PhilippC/keepass2android#492]
Just switched to Android 9 Pie, and it seems like when I try to open up the k2a keyboard and press the lock button to select an entry, the pop-up is hidden underneath the contents of the current app. Was not an issue before 8/6. Can still click on bottom element and cancel button, but text is not visible for bottom button. On a Pixel 1, August security update. Tested across multiple apps and phone restart.

**Comment by solikeumyeah** [comment]
Same issue here immediately after upgrading to Android P.

![screenshot_20180809-220735](https://user-images.githubusercontent.com/9821269/43898686-f498803a-9c22-11e8-8fed-fe962592218f.png)

**Comment by drewchapin** [comment]
I have the same issue. Here some more screenshots. For me I can't see any remnant of text whatsoever on the popup  Since most app login screens are white, the popup itself is difficult to see. Please feel free to contact me me if you need an Android 9 / Google Pixel 2 tester or additional information.

![1836006156](https://user-images.githubusercontent.com/17884678/43995255-ad46b31c-9d78-11e8-8614-bbd3f3d3ee19.png)
![screenshot_20180811-150114](https://user-images.githubusercontent.com/17884678/43995258-b4a16184-9d78-11e8-9ba9-95cf13dc0010.png)

**Comment by tggjifdhn** [comment]
This is referenced in #377 and part of 1.07 milestone.
