### ISSUE TITLE
App crash on unlocking database with fingerprint on Oreo

### ISSUE THREAD

**Issue by Marijn94** [PhilippC/keepass2android#50]
App crashes when touching the fingerprint scanner, unlocking the database with password does work.
Nexus 5X on Android 8.0.0. It did work on Nougat.

**Comment by wolfman7000** [comment]
I can confirm this issue on Android 8. For me the crash only happens if I previously added another finger in Android Fingerprint settings, and then try to open an existing database with fingerprint unlock in keepass2android.

Steps to reproduce the error:
.) Smartphone with Android 8.0 (I've tested Nexus 5X and Google Pixel)
.) Keepass2Android in Version 1.02
.) make sure fingerprint unlock in Android settings is active for the device
.) Open Keepass2Android and set up a database with fingerprint unlock
.) the crucial step: add another finger in Android i.e. "Settings / Security & location / Pixel Imprint / + Add fingerprint"
.) Open Keepass2Android and unlock the database with fingerprint
==> App crash

**Comment by mrrsm** [comment]
I have the same issue on a Pixel XL. 
For me the fingerprint works for quick unlock but not the initial unlock.  The initial unlock just crashes the process.

**Comment by Zonciu** [comment]
+1
Device：Xiaomi MIX2，MIUI8，Android 7.1.1
Exception place：
keepass2android.FingerprintDecryption.Init()

**Comment by PhilippC** [comment]
@mrrsm, @wolfman7000 Can you try to collect a logcat please?

**Comment by wolfman7000** [comment]
Hi Philipp,
can you be a bit more specific what you need? I've cleared the logs, forced a crash in keepass2android, zipped the logs (audit, dmesg, event, logcat, modem) and transferred them to my PC. But they are either empty or contain no information related to keepass2android. As the device is not rooted I can not get the kernel.log (I do not want to root the device)...

Please provide me more information what kind of log you're looking for and how to obtain it, I'll be happy to assist you...

best regards
Wolfgang

**Comment by wolfman7000** [comment]
I've sent several crash reports to Google in the last two days, maybe you can check for them in developer console?

**Comment by mrrsm** [comment]
Here is the relevant looking error from the main log that I see.  I have attached the main log with what I believe is all the relevant info.  If you need something more I can get you more info over the weekend.  [logcat.txt](https://github.com/PhilippC/keepass2android/files/1402776/logcat.txt)

> 10-20 13:16:28.665 31946 31946 I MonoDroid: Java.Security.GeneralSecurityException: Exception of type 'Java.Security.GeneralSecurityException' was thrown. ---> Java.Lang.Exception: Key user not authenticated

**Comment by Zonciu** [comment]
Same as #37

**Comment by marcelser** [comment]
Was this really fixed? It even crashes on my Samsung S8 Oreo without adding a new finger

**Comment by jaimehrubiks** [comment]
It crashes on redmi 4 pro in 8.1 when setting up fingerprint

**Comment by Zonciu** [comment]
@marcelser @jaimehrubiks My phone is ok(XiaoMi Mix2, MIUI 9.6.2.9, Android 8.0.0), try reset the fingerprint or reinstall the app

**Comment by jaimehrubiks** [comment]
Got it.

I leave my logfile in case it helps debugging.
