### ISSUE TITLE
Keyboard handles additionally fields complicated

### ISSUE THREAD

**Issue by Offerel** [PhilippC/keepass2android#542]
With one of the latest versions (maybe beta), the handling of the keyboard was changed belonging to the usage of additionally fields. Before that, i had buttons for username, password and a button to call a fly-out menu with additional fields. Since i make huge usage of additional fields, this was great.

Since the update i have the buttons for username and password and a really small button which i must click several times to reach some custom fields. Additionally the place on the button is to small, to handle longer fieldnames.

Is there a way to get back the old behavior?

**Comment by PhilippC** [comment]
if you have 1.06f (which came out yesterday on the beta channel) AND you have Android 8 or lower, you can still use the KP2A-key to get the dialog as before. If you have Android 9, unfortunately that dialog does not work anymore as before. The ">" button is a workaround that.

**Comment by Offerel** [comment]
Great. I see now the button on the S7 Edge. I hope you can find a way for Android P, since will change to Pixel device next month.

**Comment by kleinarne** [comment]
@PhilippC, would it be possible to configure which fields are shown by default, shown, or hidden? Since I use the Kee Firefox plugin and TOTP, I sometimes have a rather large number of fields to scroll through before I find the one I'm looking for.

Alternatively, you can evidently still change the height of the keyboard in Android P, so maybe additional rows could show additional fields?
