### ISSUE TITLE
Add single file permissions scope for Google Drive

### ISSUE THREAD

**Issue by justinwhite** [PhilippC/keepass2android#622]
There is an option to select a single Dropbox folder, "Dropbox (KP2A folder)", to avoid granting KP2A full access to your entire Dropbox. 

Have we considered doing something similar for Google Drive? I would assume we could use the [https://www.googleapis.com/auth/drive.file](https://developers.google.com/drive/api/v2/about-auth#what_scope_or_scopes_does_my_app_need) scope to implement this, but I haven't dug into the internals of KP2A yet.

**Comment by dayvan** [comment]
Yeah, it's a bit overkill to give access to all files.
This is what is requested when I try to selected a database on Google Drive through KP2A:
[Screenshot](https://user-images.githubusercontent.com/1678049/50710838-6ba50500-106c-11e9-889c-a53f467528f7.jpg)

**Comment by waleedsamy** [comment]
+1

**Comment by paulomartinho** [comment]
+1

**Comment by jacopotediosi** [comment]
I just checked into it.
Premise: I am just a random person and not an Android Dev, so don't put too much expectation on my words (and please correct me if I'm wrong).

If we remove full gdrive access permission in favor of single file scope permissions, we lose the ability to list files and to select them from the keepass2android custom file picker.

As stated [here](https://developers.google.com/drive/api/v2/about-auth#migrate_an_existing_app_to_a_recommended_scope) and [here](https://developers.google.com/drive/android/deprecation#file_picker_ui), we will need to implement the Storage Access Framework (SAF) and to [gain persistent access to the picked files](https://www.techotopia.com/index.php/Accessing_Cloud_Storage_using_the_Android_Storage_Access_Framework#.EF.BB.BFGaining_Persistent_Access.EF.BB.BF_to_a_File).

Migrating to this new system will require Google Drive to works in a way completely different than the others File Providers, not using anymore the keepass2android custom file picker.
At the moment I don't know an easy way to implement this (but if someone could tell me suggestions, maybe I can try).

Note also that starting from Android 11, Google will probably force to use SAF and we will need to edit also the local file picker system to adapt (I think that at that point, local file picker, google drive and maybe other File Providers that supports SAF will become a single button on the provider selector screen).
For example, I found [here](https://www.dropboxforum.com/t5/Discuss-Dropbox-Developer-API/why-using-Intent-ACTION-OPEN-DOCUMENT-does-not-list-the-Dropbox/m-p/209654) that some users are asking to Dropbox to support SAF.

As a temporary workaround, I found that if you don't want to give keepass2android full Drive permissions, you can already use SAF, which will be opened instead of the system file picker if you use Android>=9 (?). Then you can select "Google Drive" from the menù and select your keepass database from there. I tested it for a while, all functions seem to work.

![Screenshot](https://us.v-cdn.net/5019960/uploads/editor/61/lxbhab2kmjhx.png)

**Comment by luzidchris** [comment]
Hi guys,

Maybe I misunderstood but my impression is that the app is not supposedto request full access to Drive anymore since 1.08 or 1.09, is that correct?
I've just installed 1.09c via Google Play on Android 10 but I had to grant full access to Google Drive and Google account to sync with Drive. That left me with a bad feeling. It's not that I don't trust the developers of the app but nobody's perfect and there might be a security issue sometime... That's why I searched for more info on the permissions issue and found this thread.
For now, I've simply created another Google account but that's not really a satisfying solution.

Do I need to install a different version or hasn't this been changed at all?

**Comment by jacopotediosi** [comment]
> Hi guys,
> 
> Maybe I misunderstood but my impression is that the app is not supposedto request full access to Drive anymore since 1.08 or 1.09, is that correct? I've just installed 1.09c via Google Play on Android 10 but I had to grant full access to Google Drive and Google account to sync with Drive. That left me with a bad feeling. It's not that I don't trust the developers of the app but nobody's perfect and there might be a security issue sometime... That's why I searched for more info on the permissions issue and found this thread. For now, I've simply created another Google account but that's not really a satisfying solution.
> 
> Do I need to install a different version or hasn't this been changed at all?

#42 and #51

**Comment by maltem-za** [comment]
@luzidchris and anyone else with the same question, here are steps you can follow to remove KP2A's full access to your Google Drive and switch to restricted access:

1. Make sure your KeePass DB is fully saved, synced and closed on all of your devices
2. Using the Google Drive web interface or app, rename your KeePass DB file, for example to <current_name>_old.kdbx
3. Using the Google Drive app on your mobile device, download the renamed database file to local storage
4. Open KP2A and you should land on the start screen with the "Open file..." and "Create new database..." options (if not, you need to choose the "Change Database" option, or you may need to close your database or cancel out of QuickUnlock first)
5. Remove the database that you renamed in step 2 from the list of recent databases (it should be displayed starting with "gdrive://...")
6. Optionally, delete any local backups of the database (see "Show local backups" toggle at the bottom of the screen)
7. Go to https://myaccount.google.com/connections and remove all access for KP2A
8. Return to KP2A and select "Open file...", then select the **locally stored** file you downloaded in step 3 and unlock the database
9. Go to Settings > Database > Export database... > Keepass 2 database (.kdbx), then choose **Google Drive (KP2A files)**
10. Tap OK in the dialog that opens, then choose your Google account and authorize
11. You should land on a screen with "Root" at the top - enter the new database filename (eg: <original_name>.kdbx) at the bottom and click the save icon
12. KP2A will export the database and you can confirm at https://myaccount.google.com/connections that it now only has restricted access
13. Close the still opened database in KP2A, remove it from the list of recent databases on the start screen and optionally delete its local backups (as in step 6)
14. Delete the **locally stored** file you downloaded in step 3 from your mobile device
15. Return to the KP2A start screen, select "Open file...", then select the option **Google Drive (KP2A files)** - you should only see the file exported in steps 9-11, which you can now choose and open

As an additional tip, I recommend you lock the old and renamed database file in Google Drive so that no further edits are possible (or you can of course delete it, but you may want to wait until you're sure everything is OK with the new file). This will prevent you from potentially modifying the wrong file in future. I also use the "Manage versions" functionality in Google Drive to keep some older versions forever, for extra safety.

**Comment by Spiralpine** [comment]
@luzidchris - Thank you for your detailed write-up. A few questions:

1- When installing a brand instance of KP2A on a device, what should then be selected per this [screenshot](https://user-images.githubusercontent.com/1678049/50710838-6ba50500-106c-11e9-889c-a53f467528f7.jpg) ? Deny or Allow?

2- Can the KP2A DB reside in a sub-folder of GD (as opposed to under its root as a single file) to get the restricted access? (your step 11 seems to suggest the DB can only be exported the GD root folder, if I read it correctly).

3 - Any comment on what the SAF method @jacopotediosi has outlined up-thread? 

TIA.

**Comment by maltem-za** [comment]
@Spiralpine You're welcome

1. I would say deny as it is requesting full access there, although you didn't mention how you arrived at that screen.
2. I'm not sure. I couldn't see a way to navigate to a subfolder, which makes sense as listing the contents of your Drive would require full access again. Maybe one can enter a path with slashes rather than just a filename? I didn't try as I'm happy with it being in the root.
3. I don't really know enough about how SAF works. As far as I understood, it just means KP2A will access the file in local storage and any syncing will be left to Drive. I'm not sure if there are any disadvantages with this, but I imagine you could run into trouble if you modify the DB concurrently on different devices... maybe. Direct access seems safer to me as KP2A also has mechanisms built in for safe syncing.

**Comment by jacopotediosi** [comment]
> 3\. I don't really know enough about how SAF works. As far as I understand, it just means KP2A will access the file in local storage and any syncing will be left to Drive. I'm not sure if there are any disadvantages with this, but I imagine you could run into trouble if you modify the DB concurrently on different devices... maybe. Direct access seems safer to me as KP2A also has mechanisms built in for safe syncing.

I have been using the SAF method for over three years and have never had concurrency problems with any of the 3 Android devices I have had.

**Comment by Spiralpine** [comment]
@jacopotediosi - As I mentioned above, my native android file picker does not list anything under my GD root. It shows its content as empty. So, the SAF method appears to be not workable for me. (Just to note that I'm against installing any 3rd party file picker app for security reasons, hence sticking only with the native android file picker).

**Comment by jacopotediosi** [comment]
> @jacopotediosi - As I mentioned above, my native android file picker does not list anything under my GD root. It shows its content as empty. So, the SAF method appears to be not workable for me. (Just to note that I'm against installing any 3rd party file picker app for security reasons, hence sticking only with the native android file picker).

Then something is wrong with your device. SAF is a well-established Android API.

**Comment by Spiralpine** [comment]
@jacopotediosi - Can you still use fingerprint for DB authentication when using SAF?

**Comment by jacopotediosi** [comment]
> > 3. I imagine you could run into trouble if you modify the DB concurrently on different devices... maybe. Direct access seems safer to me as KP2A also has mechanisms built in for safe syncing.
> 
> I believe you are correct, @maltem-za - I tried changing the DB on one device and then trying to access it from a different device (using the system file picker on both devices0. I got an error on the 2nd device saying:
> 
> "Could not save to source file: open failed: EACCESS (permission denied). Save again or use the synchronize menu when file is accessible again."
> 
> I've never gotten this kind of error before when using multiple devices and the same DB on GD via GD API.
> 
> The DB modification timestamp on GD also never changed.
> 
> I'll stick with the "restricted access" method as it just works when the DB is accessed by multiple devices like in my environment.
> 
> Thanks again for your help.

Again, something is wrong with your setup. I daily  use SAF on two phones and access the same DB from two computers too. I often happen to add or modify entries from one device a few moments after closing the database from another device. I have never had time concurrency problems at all.
