### ISSUE TITLE
Add a button to scan an OTP QR code

### ISSUE THREAD

**Issue by ror3d** [PhilippC/keepass2android#623]
There's no easy way to do this right now, as the QR scanner only scan a whole key entry.

A way to do this might be to start from the QR code plugin and use the example from https://github.com/PhilippC/keepass2android/blob/master/docs/How-to-create-a-plug-in_.md#modifying-the-entry-view so the edit page has an additional button to scan the QR, which then should create the `otp` key with the scanned value.

**Comment by yix** [comment]
otp field supports URI scanned from QR code. I believe this issue is irrelevant and can be closed.

**Comment by derhintze** [comment]
@yix can't find any OTP field?

**Comment by yix** [comment]
@derhintze, you have to create that field manually. In the edit dialogue of the password entry use "Add additional string" button. In the "Field name" type "otp" without quotes and "Field value" should be URL-like string scanned from the QR code.

**Comment by IncPlusPlus** [comment]
> @derhintze, you have to create that field manually. In the edit dialogue of the password entry use "Add additional string" button. In the "Field name" type "otp" without quotes and "Field value" should be URL-like string scanned from the QR code.

I think it might be nice to have a simpler way of doing this such that one wouldn't have to create this field manually and a button to scan a QR code when creating or editing an entry would scan for a QR code. If successful, the relevant OTP-related fields would be created and populated with the info provided by the URI. I think it'd be worth it to keep this issue open.

**Comment by DAE51D** [comment]
For the love of God please figure out how to scan a QR code. It's becoming a requirement these days and trying to "scan" a code on a web page to get this is an exercise in frustration.

Related, simplify the way to add a text code string with a dialog prompt too

**Comment by PhilippC** [comment]
It shouldn't be too hard to use any other QR scanner app, copy the data to clipboard and paste it in KP2A? 1.09a (see https://play.google.com/apps/testing/keepass2android.keepass2android if you haven't received it on the regular Play store channel yet) has support for adding OTP fields.

**Comment by DAE51D** [comment]
Not the same my man. It’s already cumbersome to set the `otp` key/value manually. This should be way more streamlined and easier for people to use. All the other OTP apps have this basic functionality.

**Comment by WebworkrNet** [comment]
From a usability perspective, I can absolutely understand this feature request. The goal should be to make the barriers as low as possible. Especially for not so experienced users, it can fail because of such little things. I speak from experience in my environment. If something is awkward or doesn't work, such users quickly get frustrated and give up. And that is or would be a pity, because the app should be helpful to as many people as possible.

**Comment by saudiqbal** [comment]
So what you are saying is this feature is never going to be implemented? If not I have to look for a different app, since I use KeepassXC to sync between PC and Phone. If someone is not smart enough to use keepass2android then they should not be using the app, keepass is for smart users who want to have a good password manager.

**Comment by PhilippC** [comment]
no decision is made so far. In the past I decided to avoid required permissions as much as possible, but since Android 8 or so camera permission is only required when actually used, so this would now be possible. I'm wondering how often you guys are scanning such QR codes?

**Comment by ror3d** [comment]
I don't really use QR scanning tbh, since it wasn't available in the android app I've just been having to find the actual OTP key whenever I add a new one and use that on the computer application to add an OTP field.

Since most times I add a new password I do it from the computer, using the QR scanner would only make sense if it was streamlined in the app. Since until now it means having to use whatever scanner, copying the scanned value, going to k2a, creating the otp field, and pasting it there, it's simpler even to find a web app that scans the QR and gives me the key in the computer if the OTP provider doesn't give the key itself.

In my case I don't use the phone much, so this is the simplest way for me to do this. I don't doubt that other people might use it more though.

**Comment by DAE51D** [comment]
> I'm wondering how often you guys are scanning such QR codes?

With respect @PhilippC, this statement is completely baffling to me. EVERY MFA enabled site/service (aside from the useless SMS ones) displays a QR code (and rarely the `oath:` type key code to manually enter; if they do it's an exercise in hunting to find it in some hidden little link or something non-obvious). QR is literally how this security feature works to make a complex process trivial (for wider adoption). 

Currently, in order to get the keycode into KeePass, I have to use a 3rd party app (I'm now using [Authenticator Pro](https://play.google.com/store/apps/details?id=me.jmh.authenticatorpro) as [Authenticator+](https://play.google.com/store/apps/details?id=com.mufri.authenticatorplus) has gone dark). Then I scan the barcode and save a new entry. Then I have to load up the entry and copy the URL out to something where I can extract the key portion. THEN I have to annoyingly create a manual key in KeePass2Android to paste the key itself. Or alternatively I have to paste that whole `oath://` bit into something like Google Keep so that I can then load it up on my PC and into the real KeePass PC app which can handle that URI. The whole process is frustrating and way more complicated than it should be if you just did what the plethora of [Authenticators](https://play.google.com/store/search?q=authenticator&c=apps) already do -- which really is fire up a QR Code reader (ideally a built in one to your app), and parse out the URI accordingly. This really shouldn't be such a big debate or discussion. Your app is literally in the business of storing credentials and OTP / MFA is the next layer of security requirement. The irony is you already handle the 'hard part' of generating the 6-digit codes! This part should be trivial and is a solved problem to incorporate.

**Comment by derhintze** [comment]
> you already handle the 'hard part' of generating the 6-digit codes

May I ask where the codes are generated in the app? Can't find it.

> Your app is literally in the business

Nope, it's not in any business, as it's created voluntarily in the free time of @PhilippC .

Overall, I read your comments @DAE51D as demanding and snarky. While I think feedback and feature requests are welcome here, I'm also confident that a more polite way of providing it may help the case more. Are you a paying customer? (There isn't such thing here) Plus, why not make this a nice place anyway? Also, you are free to submit a PR with an implementation of what you want.

**Comment by DAE51D** [comment]
> > you already handle the 'hard part' of generating the 6-digit codes
> May I ask where the codes are generated in the app? Can't find it.

Presuming you set them up via the complicated method described above in my "snarky" reply...

![image](https://user-images.githubusercontent.com/59640592/129761205-eaef3704-482a-4715-9d83-825f73953454.png)
or also pull your notification shade down and it's there
![image](https://user-images.githubusercontent.com/59640592/129761606-97f113e1-7514-4b1e-bff2-fcce52db930f.png)

> > Your app is literally in the business
> 
> Nope, it's not in any business, as it's created voluntarily in the free time of @PhilippC .

It's a figure of speech. "_In the business of..._" means that is what the purpose of this particular credential storage app is.

> Overall, I read your comments @DAE51D as demanding and snarky. 

Then read it again. No "snark" intended, and not "demanding" either. Suggesting and illustrating the current pain point.

> While I think feedback and feature requests are welcome here, I'm also confident that a more polite way of providing it may help the case more. Are you a paying customer? (There isn't such thing here) 

Actually you're wrong. I *am* a paying customer. I have donated probably $20 USD every time the "nag screen" on his birthday or whatever comes up every year, for several years now. I fully support this app and that is why I want it to succeed and work better so that I can confidently recommend it to my less technical friends and family. Currently I can't do that. 
![image](https://user-images.githubusercontent.com/59640592/129762226-aa3fba06-8647-46f5-bddc-fa276c74e29d.png)

> Also, you are free to submit a PR with an implementation of what you want.

That's a cop-out reply. Obviously if I could write an Android application I would. I'm literally a Sr. Software Engineer -- just not in Java or Kotlin or whatever this is written in.

But we digress... The point is, the application should be able to scan a QR Code for MFA/OTP/2FA whatever. The other ones like LastPass, DashLane, etc. all do that currently. It's where the security industry is moving towards. This shouldn't even be a debate in the year 2021. It should just be a road-map item to a robust and powerful application we all depend on daily.

**Comment by saudiqbal** [comment]
I have the same problem, copy the code from the website, paste it into keepassxc and they sync it back to android.

**Comment by WebworkrNet** [comment]
It is also annoying that there are certain services that rely exclusively on QR codes. There is no provision for manual set-up. But that's just a side note ...

**Comment by emartinm** [comment]
I agree that adding support for scanning QR codes to automatically populate the TOTP values (secret, length, time) of the entry would be a great usability improvement. Currently I scan the QR code with Lens or Barcode Scanner to obtain the `otpauth://XXXX` URL and then I paste it in the field, but for standard (non-expert) users that may be complex and confusing. I also agree that scanning QR codes is the simplest, most natural and less error-prone way of reading these values when configuring 2FA for a service using any TOTP app.

I perfectly understand @PhilippC concerns about minimizing the number of permissions required, but it's true that with the new permission schema it's more clear that the app only needs to access the camera because you want to scan a QR code. Additionally, if this permission is finally added then something similar could be applied to adding photos as attachments that are taken on the fly using the camera instead of previously taken and stored in the phone (I'm thinking for example adding directly a photo of a credit card or other sensitive document).

**Comment by segevfiner** [comment]
Might be helpful https://developers.google.com/ml-kit/vision/barcode-scanning/android, there might be sample code for an activity that uses it somewhere. There is also the ZXing library but it's in maintenance only mode.

**Comment by saudiqbal** [comment]
Hopefully @PhilippC is still maintaining this project and adds this feature.

**Comment by PhilippC** [comment]
I suggest you react with thumb-up on the very first post of this issue to push this up on https://github.com/PhilippC/keepass2android/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
