### ISSUE TITLE
Enhancement suggestion: - switch to keepasskeyboard for inside keepass2android

### ISSUE THREAD

**Issue by Opensourcecommunitydevelopment** [PhilippC/keepass2android#67]
popular Keyboards like GBOARD or Swype and whatever other do share and save words and even portions of typed in keys into cloud/ send back to Googles or save locally suggestion words database. 
for anything inside keepass2android database should be kept secure, this is a type of 3rd party leak. having use of keepasskeyboard by the autoswitch plugin would be a nice option for some extra security preventing leaked information that only should be inside the encrypted database.

another reason, if someone looking about your shoulder, if the keyboards poppes up any letter pressed in big, this reveals your typed info easily, especially while password unlocking.

**Comment by KonradAdamczyk** [comment]
I will split this topic  into two issues:
1. A security bug  - Lack of dedicated keepass2android keyboard when typing database master password. Because it reveals master password to keyboard provider.
2. An enhancement - Lack of dedicated keepass2android keyboard when typing other sensitive information inside keepass2android database. Because many people are using keepass2android as read only for their databases, and editing sensitive data is not pretty common, so it can wait.

A temporary quick fix for this can be incognito keyboard mode:
https://www.xda-developers.com/api-apps-keyboard-incognito-mode/
so that at least sensitive data will not be stored as learnt phrases, but this can not guarantee that keyboard provider will not capture sensitive information.

@PhilippC 
Please assign high priority at least for issue number 1.


Issue number 1 is stopping me from using keepass2android.
