### ISSUE TITLE
Browser password autofill not working correctly when searching for entry with URL

### ISSUE THREAD

**Issue by Topher2014** [PhilippC/keepass2android#687]
I select the lock icon, select what would normally be "select from url", and keepass selects the correct entry and takes me back to the login. The username enters correctly, but password enters "framemonitorsticker".
If I go back into keepass and click the eye icon to see my password, then when I go back to the login the password enters correctly. If I search for an entry manually then the password enters correctly.
This only seems to effect browsers; the autofill feature in apps works correctly.
Incidentally, I said "what would normally be 'select from url'" because I'm also experiencing the bug that is causing the dialogue boxes to display incorrectly, #641/377.

Essential Phone running updated, unrooted Android Pie 9
Browser is Google Chrome

**Comment by Topher2014** [comment]
No, I wasn't using the share url from the browser menu, I actually didn't realize you could do that. I would click the lock icon and then select the option (in the keepass dialog box that comes up) to search for entries with the matching url. And yes, I would click the username box and then click the "username" and "password" icons on the keepass keyboard.
The "issue" is actually different than I described though and I figured it out. This is a bit embarrassing, but it turns out "framemonitorsticker" was actually my GitHub password (obviously I changed it before posting this message) 🤦‍♂️. I have a ton of entries with the same username for many of them, and I don't know virtually any of the passwords.
It looks like all of those urls I had saved using the method above changed. So, for instance, when I searched by url on protonmail.com it used "ch.proton.android" or basejumper.com used "basejumper.com". Now if I use the search by url selection it's using "com.android.chrome" for every website, and the only entry that has that is my GitHub entry so it was selecting that. If any of that makes sense.
It seems like that's probably because of a Chrome or Android update? Either way, thank you for the reply. In an indirect way it helped me figure out what was going on, plus I think the browser menu way is even faster.

**Comment by gabrielambuehl** [comment]
I can confirm that in the latest pre release, searching for a site in the Keepass2android gui and then switching to the browser ends up with a keyboard that forgot all about the site.

With the share menu it always worked for me.

**Comment by PhilippC** [comment]
@gabrielambuehl do you still have thi for 1.07-pre8?

**Comment by JohnLGalt** [comment]
I do - I'm the one that also, in my ßeta testing Google account, mentioned that I would be making a post here.  Luckily, I figured out how to find the issues related to that build specifically, and found this thread.

With me, I have several Google accounts entered into my KeePass database.  Using the stable release, and switching to the KeePass native KB, I am able to select (or pre-select) a database entry and use the quick entry buttons from the minimal KB to enter username, PW, and even OTPs.

When I have installed the ßeta version (and this has been happening for a while, every time I have tried the ßeta  version for at least the last few months), upon switching to the KeePass native KB, instead of giving me that minimal KB I get the full KB.  And even if I have already pre-selected the database entry that I wish to use, upon hitting the lock icon to change to the minimal KB, it tries to get me to select a database entry - no problem there.  However, upon selecting entry, it will enter the username correctly, and after I hit submit, it enters the username instead of the PW in the PW field - I've tried numerous variations on settings with the 107-pre release, and it always fails.

Caveats:  When this was occurring with me previously, I was running Android Pie (latest) full-stock, no root, locked bootloader, no customer recovery, nothing - all fully stock.  My device is a Taimen, aka Pixel 2 XL.  However, this most recent attempt to use it is on the Android Q DP1 release, which I took as an OTA over the stock Pie, and the BL is now unlocked (because I have rooted the device).

What I am doing (was trying to do) was set up all of the different Google accounts I have - I have 2 personal Google accounts, 2 shared Google accounts (one login that I share with my family) and 5 Google Apps (er, G Suite) accounts.  I navigated to Settings --> Accounts --> Add account, select Google as type, and then authenticate myself on my phone, and from there attempt to add a new account.  With 107pre, I get the errors as above.  with 106 stable, I manually open the database, pre-select the account I want to add, and then use the minimal native KP KB and am able to add the account successfully, including OTPs (on 2 accounts that are not bound to my Titan Security key yet).

Hope this is enough information, if you need anything more (logs, etc.), or want me to test specific settings in 107pre again, let me know - I'm glad to help troubleshoot.

**Comment by PhilippC** [comment]
cannot reproduce any of the issues described here. Please reopen if you can provide more information.
