### ISSUE TITLE
High Memory usage using Quick Unlock

### ISSUE THREAD

**Issue by Ralph-M1** [PhilippC/keepass2android#70]
I'm using a Xiaomi Mi Max running on Lineage OS 14.1 (7.1.2) and this was the usage a few days back with auto fill and quick unlock enabled. It was touching about 630 mb of ram usage. 
![screenshot_20171019-074753](https://user-images.githubusercontent.com/33055703/31936254-ad295586-b8ce-11e7-8395-2bf269c33f9a.png)

Now, after a few days aand after disabling Auto fill, restarting and only keeping quick unlock on, this is the memory usage.
![screenshot_20171024-091040](https://user-images.githubusercontent.com/33055703/31936337-e90c4144-b8ce-11e7-80dd-8fc740f74264.png)

Please do check if this is normal usage now as I'm not really sure but it looks a bit high IMO. Please let me know if you want any logs or anything as I'm not sure how to generate logs in the keepass app 

Edit: as on today, 25 Oct 2017, the usage has suddenly spiked to 599 mb

![](https://i.imgur.com/xXpfOqk.png)

Edit: after updating the app, the memory usage is only 95 mb .

Edit: closing and reopening the database has now taken memory usage to 355 mb..

**Comment by matkam** [comment]
I'm still seeing some large memory usage by Keepass2Android with quick unlock. Why did this issue get closed?

**Comment by jvandenbroek** [comment]
Can confirm that after running / using it for a while, memory usage increases a lot. Normally it's about 80-90MB, which is fine, but currently it's using 355MB. That seems a bit excessive.. Maybe caused by merging changed copies a few times, not sure. Not sure how I can help to provide more useful info?

**Comment by DiGitHubCap** [comment]
I can confirm this issue as well. RAM usage seems to go up over time, and the app is currently using 1.3GB on my phone. This is very annoying because it restricts the number of apps I can run at once, and sometimes even results in the Keepass2Android process terminating in the background, so I have to type the full password again. I can provide more information if needed to help debug and resolve this issue.
