### ISSUE TITLE
saving stops, if keepass2android looses focus

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [PhilippC/keepass2android#719]
when another app gets into foreground, i found a saving database wasn't saved. Could the saving progress be threaded in background? 
Bonus:

if saving works in background.. You can make changes and continue using your database!

**Comment by usnbrendon** [comment]
Philipp, 
I can corroborate this fact, as this impacts me ROUTINELY!  It's maddening.  Lemme post what logs I currently have and I'll grab additional info for you as necessary to help troubleshoot.  

Wow....
Okay, so I'm NOT posting the log output from KP2A.....it crashes every single time I select the option to export / send logs.  I mean....WTH?!    I realize I am on latest beta build but I know the KP2A crash during sync/save to external (Dropbox in my case) upon KP2A losing focus to another Android app, existed well prior to the past 3 beta releases because I've personally sent multiple feedback reports over the past year+ regarding the bizarre KP2A crashes during Sync/Save issue.   Unfortunately, I hadn't really thought about the aspect of KP2A crashing only when it becomes the BACKGROUND app while performing it's sync/save encryption routine until taking the time to dig into the forum and noting others' bug / error reports.   Only then did I e
recognize THIS POST fits my specific situation to a T ...  and suddenly there seems to be hope!

(Until I can't pull logs without KP2A crashes that is)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
this happens to me everytime saving locally in internal storage no clouds but using keepass2android(online!)

**Comment by usnbrendon** [comment]
I am in the same boat and it doesn't matter whether I'm saving to local file on internal device storage using standard default KP2A clean-install set-up, no advanced user options; or my preferred user customization options in KP2A with local db cached internally & mirrored to microSD  (with or without .kdbx synchronization to Dropbox to keep my laptop & tablet synced to my cell).

I literally have 24 crashes of KP2A (current beta build) recorded by Samsung's device manager and that is just since reinstalling it from scratch on the 19th of Feb.  

@PHILIPPC I've attempted to use the in-app method of generating the DEBUG LOGS to share to Dev but KP2A crashes instantly upon every attempt at collecting / sending its own freaking logs!   What to do about THAT???

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
I also experienced data loss while saving my device was locked. Afterwards I found saving not successfully. And database was locked. After unlocking my changes disappeared.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
On 8bpre1
It once worked switched tasks and keeping keepass survive saving progress.

But another I received this information of crash:

![IMG_20200617_015106](https://user-images.githubusercontent.com/46166740/84864425-f1f1b300-b076-11ea-908e-f30deacd7155.jpg)

So this seems related. Or may be is another issue.
