### ISSUE TITLE
Improve auto fill search

### ISSUE THREAD

**Issue by applesea2** [PhilippC/keepass2android#742]
Currently, Keepass2Android can only auto fill a field if it finds the exact package name of the app. Auto fill should be able to find a field by app name, url, name, etc, rather than having to set a custom url for every app.

**Comment by PhilippC** [comment]
I'm not so sure. Google even suggests to enforce App Linking when filling android apps. I think the current way is a reasonable compromise. You only have to search the entry manually once for each app.

**Comment by Karreg** [comment]
Also, using app name is a huge security issue...

**Comment by raphraph** [comment]
> You only have to search the entry manually once for each app.

After reading this I made a test (with one app only) because I had the feeling that I had to choose manually the correct entry every time.

And what I experience is the following :
1. Open app
2. Choose "fill with Keepass2Android" (because no correct result appears)
3. On the entry search results screen if no result comes out, you can either :
3.1. Tap the search bar at top of the screen, find the correct entry and select it
3.2. Tap the "Choose another entry" button at bottom left of screen, find the correct entry and select it

Apparently, when doing 3.2. it asks if you want to remember this entry for this app. But if doing 3.1. it does not ask for that, and therefore does not remember the entry for the app.
I was always doing 3.1.

Can someone confirm this ? or am I doing something wrong.

**Comment by finderAUT** [comment]
Shouldn't the autofill for Chrome search by URL? 
It always looks for Chrome's package name and I need to select the entry manually...

**Comment by andreaippo** [comment]
> > You only have to search the entry manually once for each app.
> 
> After reading this I made a test (with one app only) because I had the feeling that I had to choose manually the correct entry every time.
> 
> And what I experience is the following :
> 
>     1. Open app
> 
>     2. Choose "fill with Keepass2Android" (because no correct result appears)
> 
>     3. On the entry search results screen if no result comes out, you can either :
>        3.1. Tap the search bar at top of the screen, find the correct entry and select it
>        3.2. Tap the "Choose another entry" button at bottom left of screen, find the correct entry and select it
> 
> 
> Apparently, when doing 3.2. it asks if you want to remember this entry for this app. But if doing 3.1. it does not ask for that, and therefore does not remember the entry for the app.
> I was always doing 3.1.
> 
> Can someone confirm this ? or am I doing something wrong.

I can confirm that 3.2 is what I always did in your scenario to have my database updated. 3.1 is a simple search in the app, but won't link the results to the URL/app you're trying to autofill.

**Comment by raphraph** [comment]
> I can confirm that 3.2 is what I always did in your scenario to have my database updated. 3.1 is a simple search in the app, but won't link the results to the URL/app you're trying to autofill.

Thanks for confirmation.
This difference doesn't feel obvious to me (as a basic user). One is "Choose another entry", and the other is a _search_ icon, I don't think it is easy to guess that it does not do the same thing.
I used the app for a long time without understanding why it sometimes remembered the entry until reading this issue.
