### ISSUE TITLE
Feature: Multiple URLs for one DB entry. 

### ISSUE THREAD

**Issue by RichardMyersGV** [PhilippC/keepass2android#772]
It would be convenient to he able to store multiple URLs for a particular login. For instance, my Amazon login is used for Audible and Amazon. I could create two entries, but then I'd have to keep them both updated if something changes. Not impossible, but not ideal either.

Thanks! 
Richard

**Comment by Rookiestyle** [comment]
Unless there is a really good reason one should avoid using the same credentials for multiple sites.

If you have no other option you can try to create an additional field and simply enter the second URL.

Field name: KP2A_URL_1 (if already existing simply increase the number from 1 to 2, 3, ...)
Field value: second URL

KP2A uses these fields to add app names to existing entries so that e. g. both Amazon Website as well as Amazon app will benefit from KP2A.
I did a quick test by adding https://keepass.info/help/kb/testform.html as second URL and it worked for me.

**Comment by RichardMyersGV** [comment]
Hi,
They are one and the same entity (Amazon bought Audible), and thus use
the same credentials.  But the URLs are different...
Thank you!  I will try it.
Richard

**Comment by Karreg** [comment]
I have this use case, but I don't have your issue. I access Audible only via the application, so the default behavior is working fine.

However, one way to handle your use case is references. It requires (to my knowledge) to edit your database from keepass2 on desktop, then you can create an Audible entry, and references username and password from your amazon entry. This way you can have multiple entries, each one with its own URL, but with only one password... And the references are correctly handled by KP2A afterwards. [Here is the documentation on Keepass2 field references](https://keepass.info/%0D/help/base/fieldrefs.html).

Still, I'm very curious about why you need the URL, and not the app reference (each entry can have multiple app references)

**Comment by PhilippC** [comment]
@Rookiestyle 's hint should solve this.
