### ISSUE TITLE
Same autofill entry on every site

### ISSUE THREAD

**Issue by alanq** [PhilippC/keepass2android#774]
With the KP2A Autofill app, from a web form I selected an entry from the keepass db (it didn't suggest one that matched the url) and then accepted the prompt to remember the selected keepass entry.
But I noticed the popup confirmation message (briefly before it disappeared) only mentioned Firefox, not the specific site. Now every site autofills with the same keepassy, whenever I select Autofill through Keepass2 Android. And I cannot find where this settings is, so cannot revert to selecting a keepass entry manually from each site's login form.

Is it expected that the Autofill works on Android and Firefox? Am I doing something wrong?
Thanks

**Comment by Karreg** [comment]
Yes, you did something wrong :)

First of all, to fix the issue, you have to remove the memory in the selected entry. You have to open the first entry you autofilled this way, and you should find the reference to firefox in one of its fields. You have to remove it and save your database. There's no way to tell you which one it is, because only you know which one it is. Also, the field depends on the existing field in the first place. It could be the URL field, or another one... You will see the reference to firefox in it.

Then, you can use the correct [workflow to auto-type in browser](https://github.com/PhilippC/keepass2android/blob/master/docs/Documentation.md#browser-based-workflow). 

Or, you can try the autofill plugin, [available here](https://github.com/PhilippC/kp2a_accservice_autofill/releases/)

Feel free to close this issue when you're done :)

**Comment by PhilippC** [comment]
@alanq did you use the built-in keyboard, the Accessibility-based autofill plugin or the Autofill service which is integrated in the app (and available sinces Android 8)?

**Comment by alanq** [comment]
I used the autofill plugin. I found and removed the reference to Firefox in an entry's field as advised. I am now in rtfm phase and will report back (and close), many thanks.

**Comment by alanq** [comment]
Ok I see the auto fill plugin doesn't work with Firefox on Android. But the other methods deceived in the readme work well!
Thank you both.
