### ISSUE TITLE
Request: offline version is truly offline again

### ISSUE THREAD

**Issue by kevin789900** [PhilippC/keepass2android#86]
When I first started using this app I don't remember the offline version having checkbox for "work offline".  No menu for "work online" either.  Now when I select this, it says files are in sync.... in sync with what.... since I am using offline version?

I would like for the offline version to not have any way to connect, even through another file manager app.  I used a 3rd part file manager and now my data file is lost in space :-(

I just want to save my data file to sd card so in case my phone dies I put card into new phone.

Thanks!

**Comment by kevin789900** [comment]
I also see "remote file and cache are synchronized" popup message as I close and open new databases for testing purposes.  Is a cache needed if truly offline?

**Comment by DJCrashdummy** [comment]
i also get an error when opening _Keepass2Android Offline_, that it "couldn't load the file from the server, and will use the local cached version... and modifications will be synced later".
**this can be prevented by disabling offline-mode:** i guess this is because the local storage-backend is handled exactly the same way like an online backend.

IMHO this is an unfortunate UX and causes confusion because of the "online-features" of the offline-version... it would be better to hide/disable the sync-, online- & offline-items.
btw: **does it really make sense (also from a security-view) to cache a local file?** - the main-effect is, that the (cached) file stays accessible also after deleting the (original) file. i think this may scare some users and should be prevented! i know a deleted file is not really deleted and this is more "security by obscurity" but at least provides a better and easier understandable UX.

_and in generall i still don't get it why every second app needs to have sync-features nowadays?!? - i use one full featured sync-app for all data i need on my phone and that's it. but this is an other topic..._

**Comment by kevin789900** [comment]
> this can be prevented by disabling offline-mode

Are you referring to the option on the 'unlock database' screen: 'work offline'.  I have had that selected.

**Comment by DJCrashdummy** [comment]
@kevin789900 
yes, but also in the menu while the database is unlocked you can toggle on-/offline which will have the same result.

if i'm right, you can for example transfer (cut, not copy!) your database to another device and open it there and you will notice all changes made since you activated the "offline-mode" won't be there. and the icing on top will be, on your first device you can still open the file (with all changes you made), although it isn't there anymore! - for sure BACKUP your data before playing around!
no, that's not wizardry... you just worked the whole time with a cached version of your database, which simply means a (local) copy of it somewhere "hidden" in the system. - if you haven't noticed it, the location of the cached files can be changed in the settings; but as always at production-systems (especially for normal users): if you aren't sure and don't know for 100% what you are doing, stay with the default settings.

**Comment by kevin789900** [comment]
Sorry about the other post, I could not locate this one for some reason.  To keep this request focused on one issue I'm going to remove the "no 3rd party".  I still feel like the offline version should not have any options that indicate working online (which deselecting offline does to me at least). 

In the offline version, what happens if you deselect "work offline"?

**Comment by DJCrashdummy** [comment]
as PhilippC already explained in his https://github.com/PhilippC/keepass2android/issues/113#issuecomment-344005776, the nonet-version is NEVER working online!
have a look at your OSes app-settings (or while installing), it does not even have the permissions to do so.

and as i already explained in my first https://github.com/PhilippC/keepass2android/issues/86#issuecomment-341681095, the "work offline" checkbox is a switch to disconnect the storage-backends (which is still only local in the nonet-version, no matter what file-browser you use)!
to make it easy, you can think about the "work offline" checkbox about something like a "don't touch my original file" checkbox, although you can save changes to a "temporary" file somewhere "hidden" in the system...

@PhilippC 
as already wrote in the 2nd section of my https://github.com/PhilippC/keepass2android/issues/86#issuecomment-341681095, is it possible to set the nonet-version to always "online" and hide the net-items?

**Comment by PhilippC** [comment]
I agree that the current state is hard to understand. 
The question I see here is whether or not the Offline version should use file caching by default. @kevin789900 I guess what you actually want is disable file caching in the app settings (under file handling).

The reason for having it there is that the app uses Android's storage access framework for accessing files and this frameworks allows many different storage types, not only local but also e.g. Google Drive. To make sure users can always access their files, even if the storage access provider currently cannot (because there is no connection), I think it makes sense to cache the files. "Work online" means (as correcyly explained by @DJCrashdummy ) that changes are written to the Cache AND the original file (if possible), while "work offline" means that changes are only reflected in the app cache.

Unfortunately I cannot see through Storage Access framework if caching makes sense or not, I simply get a content URL. So what should I do? Disable caching by default? Better explain why I'm doing it?

**Comment by kevin789900** [comment]
noted earlier in this issue:
> I also see "remote file and cache are synchronized" popup message as I close and open new databases for testing purposes. Is a cache needed if truly offline?

This use of the word "remote" also adds to my confusion about whether or not truly offline.  Thank you for the discussion.  I really like the idea of this offline app for all my passwords as compared to...

https://www.forbes.com/sites/katevinton/2015/06/15/password-manager-lastpass-hacked-exposing-encrypted-master-passwords/#30f36711728f

https://paul.reviews/how-secure-is-roboform-the-5-minute-challenge/

So personally I would like the offline version to have no options for not being offline or indicating such, no references to remote files if they are not being accessed, etc.....  Same for caching too I guess, when I see that my kdbx is cached in some deleted 3rd party file manager path (which kind of looks like a URL) it concerns me.

Thanks again!

**Comment by DJCrashdummy** [comment]
@kevin789900 because of your last paragraph i'm not really sure if you finally got it... i'm trying it once again:
"remote" does not necessarily have to do with online-/web-things, it just means "not nearby"!
in your case it is not about a physical distance, but about the kind of storages... the _cached_ file is stored something like nearby in the app-related storage, and the _remote_ file is the one wherever you located it. - this may also be a sd-card or an usb-stick, in which case caching also in the nonet-version makes sense, because if you unplug the usb-stick you will still be able to access your passwords.
--> as i already said: think about the offline-checkbox as a software-plug to disconnect your storage (no matter what or where it is).

to give you some easy steps:
1. i guess your file is saved on the same physical storage (in which case caching is hardly needed)... that's why PhilippC suggested you to deactivate caching.
1. you have to be "online" in the nonet-version, otherwise no changes will be written to your file.
- the path you see is just a normal path to your file, where you located it! - and it's the other way around... URLs look like normal paths, because... well... websites are also files. :stuck_out_tongue_winking_eye: 
- i have still no idea what's your problem with the 3rd party file manager...?
    it has nothing to do with the caching. - Keepass2Android just provides it as an option to locate your stored/original/remote file (which all 3 are the same, if you sill didn't get it!)

**Comment by DJCrashdummy** [comment]
@PhilippC 

1. regarding what i wrote in https://github.com/PhilippC/keepass2android/issues/86#issuecomment-344652713 (the last bullet):

    > interesting behavior: try to open the file directly by your 3rd party file manager, so Keepass2Android detects it as local file and seems to deactivate caching and hides the offline-checkbox.

    hopefully this is correct? and also intended?

1. > Unfortunately I cannot see through Storage Access framework if caching makes sense or not, I simply get a content URL.

    you also can't see which storage-backend of Kepass2Android is setup/used?

1. > So what should I do? Disable caching by default?

    disabling caching by default for every backend would result in a regression for much users; and the more time i'm thinking about it, the more i guess it may also be useful for the local backend when using external sd-card or some other storage via usb-otg...
maybe the easiest and best solution would be just a simple question at the first start, like:
        _do you want to have your file/passwords to be accessible also when the original source-file is not reachable? yes | no?_
        _if, yes be aware, that the file is cached/copied on your device (until you clear the cache via the settings)._
        _you can also activate and deactivate this function every time in the settings._

1. > So what should I do? ... Better explain why I'm doing it?

    well, a kind of... the wording in conjunction with the local backend (especially for the nonet-version) is really unfortunate! - it would make sense to rethink it. maybe to get away from the "online-/offline-/remote-terms" more in a direction with phrasings like "storage access", "write changes to original file", "keep files in sync", "original file", "source file", etc.

btw, i guess i found a bug: while playing a little bit around with the nonet-version (no idea if the net-version is also effected) i noticed, when i try to deactivate caching, a warning is displayed, that all unsynced changes will get lost... so far so god, BUT no matter if i press _yes_ or _no_, the caching gets deactivated!

**Comment by cpengr** [comment]
@PhilippC, thanks for your prompt response over on [my issue](https://github.com/PhilippC/keepass2android/issues/175) regarding this...issue.

I think it's pretty clear that there remains confusion around this issue, based on discussion here (look how much explaining it took!), and the number of github issues reporting it. I think this stems from your overloading of the words "online" / "offline". Your [commit referenced here](https://github.com/PhilippC/keepass2android/commit/0741bcbbaac12f0b73c8eb63d7aa3661fb71a708) doesn't resolve the user confusion, AFAICT.

So, my suggestion is to stop overloading these terms in the UI, and choose from one of the following options:

1. For the offline version of the app, remove the "Work offline" option from the "Unlock database" screen. Either always enable, or always disable the caching internally (whichever makes the most sense - probably enable, I'm guessing). Just do the sane thing. Is there a reason to have the option?

2. If there is a reason to have the "online/offline" (caching?) *option* in the offline version? i.e. Does it sometimes make sense for some users to have it one way, and for other users to have it another? If so, then change the verbiage to more clearly indicate what's happening. (It's caching, right?) Definitely don't use the terms "online" or "offline" here. And clarify the error/popup messages as well.

Maybe consider also applying whichever change you choose to the "online" version of the program, in cases where the user isn't syncing with an online/cloud service. (I haven't used that version, so I'm not sure this suggestion makes sense there.) Actually, maybe "caching" is a more descriptive term there, too?

I'm not saying these are the only sensible options, but that's what occurs to me at the moment.

**Comment by DJCrashdummy** [comment]
> Your commit referenced here doesn't resolve the user confusion,...

@cpengr this is just a commit to iron out a little bug (i only mentioned during this discussion, which is bad practice - sorry for that!), but has hardly to do something with the original issue.

**Comment by Zelldon** [comment]
Hey Guys,

today I used the `Keepass2Android` application and it says me `working offline` and nothing happens. 
To quick fix this I thought OK maybe I need to go ''online''. So I changed the flag. Now I lost my last changes which is really terrible. 

I used the ''work offline'' because I thought the app would sync with some weird server which I don't know. So I wanted to avoid this. Now I realized after reading this issue that the difference lies only in direct file access and caching which is really confusing and weird. 

I mean I use the offline mode and made a backup of the keepass storage periodically, which is in this not necessary since the keepass will be never touched since the changes are only cached? Sorry but this is really non-sense to me.

Since the discussion seems to be really long I didn't read all comments but I think I understand the problem. And aggree to my last previous speakers don't use the term online/offline in this case 
OR make it more transparent that now a cached file is used and the original file is not updated.

**Comment by PhilippC** [comment]
just as a note, the term "work offline" is  adapted from Mozilla Thunderbird.

**Comment by Zelldon** [comment]
Really? I mean a mail client is intended to be working online, an password manager is not.
So online/offline terms make sense in this case of Mozilla Thunderbird BUT not in this case here?

You comparing apples with pears, the use cases of these applications are completely different.

**Comment by DJCrashdummy** [comment]
i also thought 
> the term "work offline" is adapted from Mozilla Thunderbird.

is IMHO an explanation where it came from, but no reason to stay with it.

so i have to repeat my suggestions from this https://github.com/PhilippC/keepass2android/issues/86#issuecomment-344752673 (number 4. and 3.) which even doesn't need much coding, rather more translation-work.

**Comment by khapie** [comment]
@PhilippC I used "work offline" for nearly a year because I also thought it was saving the files online somewhere. A few days ago it seems like something happened which resulted in the loss of all the entries I've made since the last time it was "working online" because I only realized then that he file was last updated last year. Is there a way to recover this, maybe you could share the location of the cache file and how I can recover these entries in the cache?

**Comment by DJCrashdummy** [comment]
@khapie i'm not 100% sure and haven't checked it, so it is more a guess:
if you may recover something (without significant more effort), it would be somewhere located in `/"sdcard"/Android/data/keepass2android.keepass2android_nonet/`.

**Comment by PhilippC** [comment]
can you please comment if you think my changes in https://github.com/PhilippC/keepass2android/commit/c8a4978b5f99161f3611005814c2527ff076a11f clarify the possible misunderstandings which lead to this issue?

**Comment by DJCrashdummy** [comment]
@PhilippC i didn't get through the whole file, but commented what i found...
