### ISSUE TITLE
Google Drive Sync: Does Not Recognize Changed File

### ISSUE THREAD

**Issue by noahajac** [PhilippC/keepass2android#882]
It seems that Keepass2Android is matching locally cached databases to their Google Drive equivalent based on some arbitrary ID from Google instead of filename. This creates the issue the if a change is done to a file from another source, like on a desktop client, this ID will change and syncing will fail. In my case it says the database is trashed.

To fix this issue I am asking for an option to be added to match database files based on their filename.

Thank you.

**Comment by JohnLGalt** [comment]
That's absolutely weird - because I've been using Drive for years to keep my database synced, and I *always* make changes on my desktop, not on my mobile devices.  And every time I open KP (both now with Google's Advanced protection enabled for my account, meaning I have to have Drive keep a local copy on my mobile devices) and before (without advanced protection, so I had KP access the file directly from Drive), I see a brief message that the file has been synchronized.  I've tested this numerous times, particularly recently after enabling Advanced protection, and it works fine on my end.

Of course, in both cases (previously direct access to Drive and now direct access to locally stored file)  I'm accessing the file by filename only.  Maybe our methodologies for sync'ing are different?  I'm willing to detail how I do it if you want to test to see if this will work for you....

**Comment by noahajac** [comment]
How are you syncing Drive with your desktop? And are you using the normal Keepass software? Those are the only things I can think will be different. I'm on Linux so I use [google-drive-ocaml-fuse](https://github.com/astrada/google-drive-ocamlfuse) to mount Google Drive and I access the database files with [KeePassXC](https://keepassxc.org). I don't see how that would cause the issue unless maybe fuse mount is doing something weird.

**Comment by JohnLGalt** [comment]
On Linux (Sabayon, Gentoo-based) I use rclone, and I'm actually using KeePass 2.4x for Windows via Wine.  I opted for rclone versus ocaml-fuse because I simply couldn't get it working correctly to see my files in my Drive account after 3 different successive attempts.  With rclone, it was a simple set up and forget, allowing for bi-directional updating which, for all intents and purposes, was identical (aka in the background, and not something I have to manually trigger) as when I am in Windows.

Quick check (I'm assuming you've done this already, but doesn't hurt to ask):  When you edit the file in KPXC, does ocaml-fuse automatically sync it up to Drive?  And if it is supposed to, does logging in to the Drive via web access show that the file has actually been updated?  That's actually how I figured out fuse wasn't working on my end when I tried it....

**Comment by noahajac** [comment]
Looking at Google Drive I see what appears to be the issue. When using keepass2android to edit the file, I can see in the files activity log that it has been edited. When I use KeepassXC, I see the old file in the trash and a new file with my changes in my drive. I'm not sure if this is an issue with fuse or with KeepassXC. But keepass2android isn't at fault here, thus I'm closing the issue.

Thanks.

**Comment by PhilippC** [comment]
Thanks for investigating this. I think that more users have run into this
problem already. If you are able to find out which program is causing this
(fuse or KeppassXC, could you open an issue on their bug trackers and maybe
post a reference here? That would be great!

Noah Jacobson <notifications@github.com> schrieb am So., 11. Aug. 2019,
15:54:

**Comment by noahajac** [comment]
Did some testing where I edited a txt file with gedit and looked at the behavior in Drive. Issue is certainly with fuse, did some digging and a [bug report has existed for awhile](https://github.com/astrada/google-drive-ocamlfuse/issues/494). I commented on it so hopefully it will get some attention.

**Comment by noahajac** [comment]
To anyone who happens upon this with the same problem. The issue in google-drive-ocamlfuse has been fixed.

Set `mv_keep_target` to `true` in your config and you should no longer have this issue.

**Comment by dnlup** [comment]
If it can help, I had the same problem too. It wasn' Keepass2Android fault. I am using KeepassXC on desktop and  the option `Backup database before saving` was causing this thing.

**Comment by nutel65** [comment]
I had the exact same issue for a while now, and none of the solutions I came across helped. For anyone still struggling with the combination Linux + `rclone mount` to gdrive (google drive) + keepass2android, here's what solved the issue for me:

Use `--vfs-cache-mode full` flag when mounting gdrive with `rclone mount` 

For example, here's the command I use to mount gdrive:
`rclone mount --vfs-cache-mode full --daemon gdrive:kp/ ~/Documents/kp/`

**Comment by JohnLGalt** [comment]
> I had the exact same issue for a while now, and none of the solutions I came across worked.
> 
> For anyone struggling with the fixing the error message `database is trashed` in keepass2android, while using Linux + `rclone mount` to gdrive (google drive) + keepass2android, here's what solved the issue for me:
> 
> Use `--vfs-cache-mode full` flag when mounting gdrive with `rclone mount`
> 
> For example, here's the command I use to mount gdrive: `rclone mount --vfs-cache-mode full --daemon gdrive:kp/ ~/Documents/kp/`

Thank you for this - drove me mad for a while after I switched over to rclone....

**Comment by jiucenglou** [comment]
i am using Keepass2 on windows and save the database on Onedrive. What should I do to correct the behavior ? Right now keepass2android cannot see last modified correctly (much older)

**Comment by esune** [comment]
Having the same issue: database is synced on GDrive across Windows/MacOS/Android and Keepass2Android just started flagging the database as trashed.

**Comment by PhilippC** [comment]
@esune that might be caused by the tool used on MacOS, see https://github.com/PhilippC/keepass2android/issues/108#issuecomment-366643293

**Comment by esune** [comment]
> @esune that might be caused by the tool used on MacOS, see [#108 (comment)](https://github.com/PhilippC/keepass2android/issues/108#issuecomment-366643293)

I'm using the official GDrive integration on both Windows/MacOS/Android so I am surprised it would cause incompatibility issues. I have not noticed this behaviour between Windows/MacOS using KeepassXC. Restoring the DB from trash works, however if there have been changes between when the file was trashed and the current state they will be lost so it is something to be careful with.

**Comment by eanveyl** [comment]
I was having this issue with KeePass XC on my pc and keepas2android. It seems that KeePass XC saves a new file and then deletes the old one (you can find them in the trash folder). If you go to Settings on your KeePass XC, under File Management, you will see a "use alternative saving method". Enable that and select from the dropdown "Temporary file moved into place". 
This fixed the issue for me.
<img width="598" alt="image" src="https://github.com/PhilippC/keepass2android/assets/69760530/e129d2d1-d908-4ebc-9e23-b73e205dbe0b">
