### ISSUE TITLE
Two windows in recent apps - prevents quick changing to last app

### ISSUE THREAD

**Issue by momsi** [PhilippC/keepass2android#912]
Just recently I encounter the following issue with kp2a:

When I open an entry in a database, I have two instances of kp2a open in the recent apps. 
Whenever I switch to the second one, it closes and directs to the homescreen. 

This is quite annoying since you can't fast switch to the last used app. 

I'm sure it has to do with the keyboardswap plugin, whenever the keepass keyboard is already activated, the second window is not there.

If I can provide anything to help, let me know. 

Kind regards, 

Momsi

**Comment by chilliger** [comment]
I can confrim. This is happening on Android 9 (LOS 16) in combination with the swap plugin. After opening a entry in the database the swap plugin stays in the recents menu. Double tapping the recents button to switch to the last app is rendered useless because now you are switching between keepass and the switch plugin.
