### ISSUE TITLE
GoogleDrive sync with Android One

### ISSUE THREAD

**Issue by Tungri88** [PhilippC/keepass2android#950]
Trying to open Google Drive with an Android One C-Phone (Motorola Vision).
After selecting the Google Account I get an error.
error message: "the name must be empty : null"

With my old Phone HTC 10 with Android 8.0 everything works fine.

**Comment by Toasbi** [comment]
Same here for my galaxy s9+. I think it started happening after the drive update and/or enabling the 2fa on the Google acc.

**Comment by JohnLGalt** [comment]
I used to use 2fa with no issues with KP2A.  However, enabling **Advanced Protection** created all sorts of issues where I could not get KP2A to access Drive content (by design of Advanced Protection).

What I do is to open the Drive app on my device, find my database, and then mark it for offline use.

I then use KP2A to pick the database using the System File picker --> navigate to the location where Drive has saved the offline copy, and use it from there.  I've done a bit of preliminary testing, and if you use KP2A to update that offline copy, Drive will sync it with the online copy.

HTH as a workaround until you get it working the way you want to.  Since I have AP enabled, this is my only recourse - but it works flawlessly, in my limited testing.

**Comment by bitmizer** [comment]
I had the same error message: _"the name must be empty : null"_ on my Motorola Moto Z2 Force. My workaround was:

1. Lock and close database
2. Select **"Change Database"**
3. Select **"Open File..."**
4. Select **"Google Drive"**
5. Select the Google account where the KDBX file is stored on Drive
**NOTE:** If _"the name must be empty : null"_ appears, select **"KILL APP PROCESS"** or remove KP2A from "Recent Apps" list and "Notifications" list (if necessary) to remove KP2A from memory. Repeat steps 2 through 5 and continue to step 6.
6. Navigate to and select the KDBX file
7. Enter the Master Password
8. If desired, set up advanced features (i.e., fingerprint, etc.)

Best of luck.

**Comment by Tungri88** [comment]
the error was gone on the next day. I cannot explain what changed, but next day everything works perfectly.
